Repository intel/intel-extension-for-transformers, pull requests merged in 2023-09, with the labels that each got.

#181 [CPP Graph] add s8 perchannel quant and kernel.
  intel_extension_for_transformers/llm/library/jblas/jblas/jit_base.hpp
  intel_extension_for_transformers/llm/library/jblas/jblas/jit_blas_epilogue.h
  intel_extension_for_transformers/llm/library/jblas/jblas/jit_blas_gemm.h
  intel_extension_for_transformers/llm/library/jblas/jblas/jit_blas_prologue.h
  intel_extension_for_transformers/llm/library/jblas/jblas/jit_blas_transformer.h
  intel_extension_for_transformers/llm/library/jblas/jblas/jit_blas_utils.h
  intel_extension_for_transformers/llm/library/jblas/jblas/jit_blas_weight_compression.h
  intel_extension_for_transformers/llm/library/jblas/jblas/jit_blas_wrapper.h
  intel_extension_for_transformers/llm/library/jblas/jblas/kernel_avx512f.h
  intel_extension_for_transformers/llm/library/jblas/jblas/kernel_ref.h
  intel_extension_for_transformers/llm/library/jblas/jblas/kernel_wrapper.h
  intel_extension_for_transformers/llm/library/jblas/jblas/xbyak/xbyak_bin2hex.h
  intel_extension_for_transformers/llm/runtime/graph/CMakeLists.txt
  intel_extension_for_transformers/llm/runtime/graph/application/common.cpp
  intel_extension_for_transformers/llm/runtime/graph/core/layers/inner_product.cpp
  intel_extension_for_transformers/llm/runtime/graph/core/layers/ip_fusion_ffn.cpp
  intel_extension_for_transformers/llm/runtime/graph/core/layers/ip_fusion_qkv.cpp
  intel_extension_for_transformers/llm/runtime/graph/core/layers/jblas_common.cpp
  intel_extension_for_transformers/llm/runtime/graph/core/layers/jblas_common.hpp
  intel_extension_for_transformers/llm/runtime/graph/core/ne_jblas.h
  intel_extension_for_transformers/llm/runtime/graph/core/ne_layers.c
  intel_extension_for_transformers/llm/runtime/graph/jblas/CMakeLists.txt
  intel_extension_for_transformers/llm/runtime/graph/jblas/jblas/jit_base.hpp
  intel_extension_for_transformers/llm/runtime/graph/jblas/jblas/jit_blas.h
  intel_extension_for_transformers/llm/runtime/graph/jblas/jblas/jit_blas_epilogue.h
  intel_extension_for_transformers/llm/runtime/graph/jblas/jblas/jit_blas_gemm.h
  intel_extension_for_transformers/llm/runtime/graph/jblas/jblas/jit_blas_prologue.h
  intel_extension_for_transformers/llm/runtime/graph/jblas/jblas/jit_blas_transformer.h
  intel_extension_for_transformers/llm/runtime/graph/jblas/jblas/jit_blas_utils.h
  intel_extension_for_transformers/llm/runtime/graph/jblas/jblas/jit_blas_weight_compression.h
  intel_extension_for_transformers/llm/runtime/graph/jblas/jblas/jit_blas_wrapper.h
  intel_extension_for_transformers/llm/runtime/graph/jblas/jblas/kernel_avx2.h
  intel_extension_for_transformers/llm/runtime/graph/jblas/jblas/kernel_avx512f.h
  intel_extension_for_transformers/llm/runtime/graph/jblas/jblas/kernel_jit.h
  intel_extension_for_transformers/llm/runtime/graph/jblas/jblas/kernel_jit_injector.h
  intel_extension_for_transformers/llm/runtime/graph/jblas/jblas/kernel_ref.h
  intel_extension_for_transformers/llm/runtime/graph/jblas/jblas/kernel_wrapper.h
  intel_extension_for_transformers/llm/runtime/graph/jblas/jblas/xbyak/xbyak.h
  intel_extension_for_transformers/llm/runtime/graph/jblas/jblas/xbyak/xbyak_bin2hex.h
  intel_extension_for_transformers/llm/runtime/graph/jblas/jblas/xbyak/xbyak_mnemonic.h
  intel_extension_for_transformers/llm/runtime/graph/jblas/jblas/xbyak/xbyak_util.h
  intel_extension_for_transformers/llm/runtime/graph/models/gptj/gptj.cpp
  intel_extension_for_transformers/llm/runtime/graph/models/gptj/gptj_utils.cpp
  intel_extension_for_transformers/llm/runtime/graph/models/llama/llama.cpp
  intel_extension_for_transformers/llm/runtime/graph/models/model_utils/arg_parse.cpp
  intel_extension_for_transformers/llm/runtime/graph/models/model_utils/model_config.h
  intel_extension_for_transformers/llm/runtime/graph/models/model_utils/model_utils.cpp
  intel_extension_for_transformers/llm/runtime/graph/models/model_utils/quant_config.h
Labels: ITREX.cpp

#221 [CPP Graph] Fix Graph Model quantization on AVX2-only Platforms
  intel_extension_for_transformers/llm/runtime/graph/models/model_utils/model_utils.cpp
  intel_extension_for_transformers/llm/runtime/graph/vectors/cpu/vec_arithmetic.cpp
  intel_extension_for_transformers/llm/runtime/graph/vectors/cpu/vec_base.hpp
  intel_extension_for_transformers/llm/runtime/graph/vectors/cpu/vec_store.cpp
Labels: ITREX.cpp

#227 Fix checkmarx security issues
  intel_extension_for_transformers/neural_chat/pipeline/tools/cut_video.py
  intel_extension_for_transformers/neural_chat/ui/basic_frontend/fastchat/serve/cli.py
  workflows/chatbot/demo/basic_frontend/fastchat/serve/cli.py
  workflows/chatbot/fine_tuning/instruction_tuning_pipeline/finetune_clm.py
  workflows/chatbot/inference/backend/chat/model_worker.py
  workflows/chatbot/inference/memory_controller/chat_with_memory.py
Labels: ITREX v1.1.1

#226 Fix the bug in rag example (Neural Chat)
  intel_extension_for_transformers/neural_chat/chatbot.py
  intel_extension_for_transformers/neural_chat/cli/cli_commands.py
  intel_extension_for_transformers/neural_chat/examples/retrieval/retrieval_chat.py
  intel_extension_for_transformers/neural_chat/pipeline/plugins/retrievals/indexing/document_parser.py
  intel_extension_for_transformers/neural_chat/pipeline/plugins/retrievals/indexing/utils.py
  intel_extension_for_transformers/neural_chat/pipeline/plugins/retrievals/retrieval/bm25_retrieval.py
  intel_extension_for_transformers/neural_chat/server/restful/finetune_api.py
Labels: ITREX v1.1.1

#229 optimize ASR audio to waveform loading
  intel_extension_for_transformers/neural_chat/pipeline/plugins/audio/asr.py
Labels: ITREX v1.1.1

#174 Added QLoRA support in NeuralChat finetuning and refined NeuralChat optimization API.
  .github/workflows/unit-test-engine.yml
  .github/workflows/unit-test-optimize.yml
  intel_extension_for_transformers/llm/finetuning/data_utils.py
  intel_extension_for_transformers/llm/finetuning/eval_utils.py
  intel_extension_for_transformers/llm/finetuning/finetuning.py
  intel_extension_for_transformers/llm/inference/inference.py
  intel_extension_for_transformers/llm/quantization/optimization.py
  intel_extension_for_transformers/neural_chat/__init__.py
  intel_extension_for_transformers/neural_chat/chatbot.py
  intel_extension_for_transformers/neural_chat/config.py
  intel_extension_for_transformers/neural_chat/tests/finetuning/test_finetuning.py
  intel_extension_for_transformers/neural_chat/tests/optimization/test_optimization.py
Labels: ITREX v1.1.1

#231 update rag readme
  intel_extension_for_transformers/neural_chat/README.md
  intel_extension_for_transformers/neural_chat/examples/retrieval/README.md
  intel_extension_for_transformers/neural_chat/examples/retrieval/retrieval_chat.py
Labels: ITREX v1.1.1

#173 [CPP Graph] Enhance beam search (length_penalty + min_new_tokens)
  intel_extension_for_transformers/llm/runtime/graph/application/pybind_gptj.cpp
  intel_extension_for_transformers/llm/runtime/graph/models/gptj/gptj.cpp
  intel_extension_for_transformers/llm/runtime/graph/models/model_utils/model_types.h
  intel_extension_for_transformers/llm/runtime/graph/models/model_utils/model_utils.cpp
  intel_extension_for_transformers/llm/runtime/graph/models/model_utils/model_utils.h
Labels: enhancement, ITREX.cpp, ITREX v1.2

#233 Fix the code structure and the plugin name in NeuralChat
  intel_extension_for_transformers/neural_chat/chatbot.py
  intel_extension_for_transformers/neural_chat/config.py
  intel_extension_for_transformers/neural_chat/examples/retrieval/README.md
  intel_extension_for_transformers/neural_chat/pipeline/plugins/prompt/__init__.py
  intel_extension_for_transformers/neural_chat/pipeline/plugins/prompt/prompt_template.py
  intel_extension_for_transformers/neural_chat/pipeline/plugins/retrieval/__init__.py
  intel_extension_for_transformers/neural_chat/pipeline/plugins/retrieval/detector/__init__.py
  intel_extension_for_transformers/neural_chat/pipeline/plugins/retrieval/detector/intent_detection.py
  intel_extension_for_transformers/neural_chat/pipeline/plugins/retrieval/indexing/__init__.py
  intel_extension_for_transformers/neural_chat/pipeline/plugins/retrieval/indexing/context_utils.py
  intel_extension_for_transformers/neural_chat/pipeline/plugins/retrieval/indexing/indexing.py
  intel_extension_for_transformers/neural_chat/pipeline/plugins/retrieval/retrieval_agent.py
  intel_extension_for_transformers/neural_chat/pipeline/plugins/retrieval/retrieval_base.py
  intel_extension_for_transformers/neural_chat/pipeline/plugins/retrieval/retrieval_bm25.py
  intel_extension_for_transformers/neural_chat/pipeline/plugins/retrieval/retrieval_chroma.py
  intel_extension_for_transformers/neural_chat/pipeline/plugins/retrievals/retrieval/__init__.py
Labels: ITREX v1.1.1

#191 Fixed import issue for seq2seq examples
  examples/huggingface/pytorch/language-modeling/inference/run_clm_no_trainer.py
  examples/huggingface/pytorch/language-modeling/quantization/run_clm_no_trainer.py
  examples/huggingface/pytorch/text2text-generation/run_seq2seq_generation.py
  examples/huggingface/pytorch/text2text-generation/run_seq2seq_generation_bart.py
  workflows/chatbot/fine_tuning/instruction_tuning_pipeline/finetune_clm.py
Labels: ITREX v1.2

#237 Add latest update in readme
  .github/workflows/script/formatScan/nlp_dict.txt
  README.md
  intel_extension_for_transformers/neural_chat/README.md
Labels: ITREX v1.1.1

#244 add README for retrieval, safety checker plugins
  intel_extension_for_transformers/neural_chat/examples/retrieval/README.md
  intel_extension_for_transformers/neural_chat/pipeline/plugins/retrieval/README.md
  intel_extension_for_transformers/neural_chat/pipeline/plugins/security/README.md
Labels: ITREX v1.1.1

#249 support adobe analytics, fix anchor issues in examples, add repo link in list
  docs/build_docs/build.sh
  docs/build_docs/source/_templates/footer.html
  docs/build_docs/source/_templates/layout.html
  docs/build_docs/source/conf.py
  docs/build_docs/source/index.rst
  docs/examples.md
Labels: ITREX v1.2

#230 [Cpp Graph]fix q8 pern QKV fusion of vnni
  intel_extension_for_transformers/llm/runtime/graph/core/layers/inner_product.cpp
  intel_extension_for_transformers/llm/runtime/graph/core/layers/ip_fusion_ffn.cpp
  intel_extension_for_transformers/llm/runtime/graph/core/layers/ip_fusion_qkv.cpp
  intel_extension_for_transformers/llm/runtime/graph/core/layers/jblas_common.hpp
Labels: ITREX.cpp, ITREX v1.2

#240 Added notebook example of NeuralChat finetuning for LLaMA2 and MPT
  intel_extension_for_transformers/neural_chat/examples/instruction_tuning/finetune_on_Intel_Xeon_CPU.ipynb
  intel_extension_for_transformers/neural_chat/examples/instruction_tuning/finetune_on_Nvidia_GPU.ipynb
Labels: ITREX v1.1.1

#243 Update NeuralChat README/Tutorial/Jupyter Notebook documents
  .github/workflows/publish.yml
  .github/workflows/script/formatScan/pylint.sh
  README.md
  intel_extension_for_transformers/neural_chat/README.md
  intel_extension_for_transformers/neural_chat/docker/inference/0001-fix-lm-head-overriden-issue-move-it-from-checkpoint-.patch
  intel_extension_for_transformers/neural_chat/docker/inference/Dockerfile
  intel_extension_for_transformers/neural_chat/docs/notebooks/chatbot_on_intel_cpu.ipynb
  intel_extension_for_transformers/neural_chat/docs/notebooks/chatbot_on_intel_habana_hpu.ipynb
  intel_extension_for_transformers/neural_chat/docs/notebooks/chatbot_on_nv_gpu.ipynb
  intel_extension_for_transformers/neural_chat/docs/tutorial.md
Labels: ITREX v1.1.1

#236 [CPP Graph] Rename LLM chat application
  .github/workflows/script/models/cpp_graph_inference.sh
  intel_extension_for_transformers/llm/runtime/graph/README.md
  intel_extension_for_transformers/llm/runtime/graph/application/CMakeLists.txt
  intel_extension_for_transformers/llm/runtime/graph/application/chat/CMakeLists.txt
  intel_extension_for_transformers/llm/runtime/graph/application/main_run.cpp
  intel_extension_for_transformers/llm/runtime/graph/scripts/run_llm.py
Labels: ITREX.cpp, ITREX v1.2

#251 Fix retrieval plugin readme and add one necessary package dependency
  intel_extension_for_transformers/neural_chat/assets/docs/sample.jsonl
  intel_extension_for_transformers/neural_chat/assets/docs/sample.xlsx
  intel_extension_for_transformers/neural_chat/pipeline/plugins/retrieval/README.md
Labels: ITREX v1.1.1

#242 Fixed lazy import issue for PyTorch in intel_extension_for_transformers
  intel_extension_for_transformers/transformers/modeling/modeling_causal.py
  intel_extension_for_transformers/transformers/modeling/modeling_map.py
  intel_extension_for_transformers/transformers/optimizer_tf.py
Labels: ITREX v1.2

#179 [CPP Graph] AMX-BF16 MHA with KV update
  intel_extension_for_transformers/llm/library/jblas/jblas/jit_blas_prologue.h
  intel_extension_for_transformers/llm/library/jblas/jblas/jit_blas_utils.h
  intel_extension_for_transformers/llm/library/jblas/jblas/jit_blas_weight_compression.h
  intel_extension_for_transformers/llm/library/jblas/jblas/jit_blas_wrapper.h
  intel_extension_for_transformers/llm/library/jblas/jblas/kernel_avx512f.h
  intel_extension_for_transformers/llm/library/jblas/jblas/kernel_jit.h
  intel_extension_for_transformers/llm/library/jblas/jblas/kernel_ref.h
  intel_extension_for_transformers/llm/library/jblas/jblas/kernel_wrapper.h
  intel_extension_for_transformers/llm/runtime/graph/core/layers/Ops.h
  intel_extension_for_transformers/llm/runtime/graph/core/layers/jblas_common.hpp
  intel_extension_for_transformers/llm/runtime/graph/core/layers/mha_dense.cpp
  intel_extension_for_transformers/llm/runtime/graph/core/layers/mha_dense.h
  intel_extension_for_transformers/llm/runtime/graph/core/layers/ne_test_layers_utils.hpp
  intel_extension_for_transformers/llm/runtime/graph/core/ne_layers.c
  intel_extension_for_transformers/llm/runtime/graph/core/ne_layers.h
  intel_extension_for_transformers/llm/runtime/graph/models/bloom/bloom.h
  intel_extension_for_transformers/llm/runtime/graph/models/bloom/bloom_utils.cpp
  intel_extension_for_transformers/llm/runtime/graph/models/falcon/falcon.cpp
  intel_extension_for_transformers/llm/runtime/graph/models/falcon/falcon.h
  intel_extension_for_transformers/llm/runtime/graph/models/falcon/falcon_utils.cpp
  intel_extension_for_transformers/llm/runtime/graph/models/gptj/gptj.cpp
  intel_extension_for_transformers/llm/runtime/graph/models/gptj/gptj.h
  intel_extension_for_transformers/llm/runtime/graph/models/gptj/gptj_utils.cpp
  intel_extension_for_transformers/llm/runtime/graph/models/gptneox/gptneox.h
  intel_extension_for_transformers/llm/runtime/graph/models/gptneox/gptneox_utils.cpp
  intel_extension_for_transformers/llm/runtime/graph/models/llama/llama.cpp
  intel_extension_for_transformers/llm/runtime/graph/models/llama/llama.h
  intel_extension_for_transformers/llm/runtime/graph/models/llama/llama_utils.cpp
  intel_extension_for_transformers/llm/runtime/graph/models/model_utils/arg_parse.cpp
  intel_extension_for_transformers/llm/runtime/graph/models/model_utils/model_config.h
  intel_extension_for_transformers/llm/runtime/graph/models/model_utils/model_types.h
  intel_extension_for_transformers/llm/runtime/graph/models/model_utils/model_utils.cpp
  intel_extension_for_transformers/llm/runtime/graph/models/model_utils/model_utils.h
  intel_extension_for_transformers/llm/runtime/graph/models/models.h
  intel_extension_for_transformers/llm/runtime/graph/models/mpt/mpt.cpp
  intel_extension_for_transformers/llm/runtime/graph/models/mpt/mpt.h
  intel_extension_for_transformers/llm/runtime/graph/models/mpt/mpt_utils.cpp
  intel_extension_for_transformers/llm/runtime/graph/models/opt/opt.h
  intel_extension_for_transformers/llm/runtime/graph/models/opt/opt_utils.cpp
  intel_extension_for_transformers/llm/runtime/graph/models/starcoder/starcoder.cpp
  intel_extension_for_transformers/llm/runtime/graph/models/starcoder/starcoder.h
  intel_extension_for_transformers/llm/runtime/graph/models/starcoder/starcoder_utils.cpp
Labels: ITREX.cpp, ITREX v1.2

#160 [CPP Graph]Enable FFN fusion
  intel_extension_for_transformers/llm/runtime/graph/models/bloom/bloom.cpp
  intel_extension_for_transformers/llm/runtime/graph/models/falcon/falcon.cpp
  intel_extension_for_transformers/llm/runtime/graph/models/gptneox/gptneox.cpp
  intel_extension_for_transformers/llm/runtime/graph/models/mpt/mpt.cpp
  intel_extension_for_transformers/llm/runtime/graph/models/starcoder/starcoder.cpp
Labels: ITREX.cpp, ITREX v1.2

#254 [CPP Graph]fix the error of convert bloom and opt
  intel_extension_for_transformers/llm/runtime/graph/scripts/convert_bloom.py
  intel_extension_for_transformers/llm/runtime/graph/scripts/convert_opt.py
Labels: bug, ITREX v1.2

#260 [CPP Graph] Fix models without jblas-based kvcache support
  intel_extension_for_transformers/llm/runtime/graph/models/gptj/gptj.cpp
  intel_extension_for_transformers/llm/runtime/graph/models/gptj/gptj_utils.cpp
  intel_extension_for_transformers/llm/runtime/graph/models/llama/llama_utils.cpp
  intel_extension_for_transformers/llm/runtime/graph/models/model_utils/model_types.h
  intel_extension_for_transformers/llm/runtime/graph/models/model_utils/model_utils.cpp
Labels: ITREX.cpp, ITREX v1.2

#209 refine example for SQ and WOQ
  examples/.config/pytorch_optimize.json
  examples/huggingface/pytorch/language-modeling/quantization/README.md
  examples/huggingface/pytorch/language-modeling/quantization/run_benchmark.sh
  examples/huggingface/pytorch/language-modeling/quantization/run_clm_no_trainer.py
  examples/huggingface/pytorch/language-modeling/quantization/run_tuning.sh
Labels: ITREX v1.2

#255 update tensorflow tests and cpp graph
  .github/workflows/optimize-test.yml
  .github/workflows/script/formatScan/pylint.sh
  .github/workflows/script/models/calculate_percentage.py
  .github/workflows/script/models/cpp_graph_inference.sh
  tests/test_tf_autodistillation.py
  tests/test_tf_distillation.py
  tests/test_tf_pruning.py
  tests/test_tf_quantization.py
Labels: ITREX v1.2

#210 [CPP Graph] ChatGLM-2 Enabling
  intel_extension_for_transformers/llm/runtime/graph/README.md
  intel_extension_for_transformers/llm/runtime/graph/application/CMakeLists.txt
  intel_extension_for_transformers/llm/runtime/graph/application/main_run.cpp
  intel_extension_for_transformers/llm/runtime/graph/core/ne_layers.c
  intel_extension_for_transformers/llm/runtime/graph/core/ne_layers.h
  intel_extension_for_transformers/llm/runtime/graph/models/CMakeLists.txt
  intel_extension_for_transformers/llm/runtime/graph/models/chatglm/CMakeLists.txt
  intel_extension_for_transformers/llm/runtime/graph/models/chatglm/chatglm1.cpp
  intel_extension_for_transformers/llm/runtime/graph/models/chatglm/chatglm1.h
  intel_extension_for_transformers/llm/runtime/graph/models/chatglm/chatglm1_utils.cpp
  intel_extension_for_transformers/llm/runtime/graph/models/chatglm/chatglm2.cpp
  intel_extension_for_transformers/llm/runtime/graph/models/chatglm/chatglm2.h
  intel_extension_for_transformers/llm/runtime/graph/models/chatglm/chatglm2_utils.cpp
  intel_extension_for_transformers/llm/runtime/graph/models/falcon/falcon.cpp
  intel_extension_for_transformers/llm/runtime/graph/models/gptj/gptj.cpp
  intel_extension_for_transformers/llm/runtime/graph/models/gptneox/gptneox.cpp
  intel_extension_for_transformers/llm/runtime/graph/models/llama/llama.cpp
  intel_extension_for_transformers/llm/runtime/graph/models/model_utils/model_files.h
  intel_extension_for_transformers/llm/runtime/graph/models/model_utils/model_types.h
  intel_extension_for_transformers/llm/runtime/graph/scripts/convert_bloom.py
  intel_extension_for_transformers/llm/runtime/graph/scripts/convert_chatglm.py
  intel_extension_for_transformers/llm/runtime/graph/scripts/convert_dolly.py
  intel_extension_for_transformers/llm/runtime/graph/scripts/convert_falcon.py
  intel_extension_for_transformers/llm/runtime/graph/scripts/convert_gptj.py
  intel_extension_for_transformers/llm/runtime/graph/scripts/convert_gptneox.py
  intel_extension_for_transformers/llm/runtime/graph/scripts/convert_llama.py
  intel_extension_for_transformers/llm/runtime/graph/scripts/convert_mpt.py
  intel_extension_for_transformers/llm/runtime/graph/scripts/convert_opt.py
  intel_extension_for_transformers/llm/runtime/graph/scripts/convert_starcoder.py
Labels: ITREX.cpp, ITREX v1.2

#262 [CPP Graph] fix broken format
  .github/workflows/script/formatScan/clangformat.sh
  intel_extension_for_transformers/llm/runtime/graph/application/main_run.cpp
  intel_extension_for_transformers/llm/runtime/graph/core/ne_layers.c
  intel_extension_for_transformers/llm/runtime/graph/core/ne_layers.h
  intel_extension_for_transformers/llm/runtime/graph/core/parallel_context.cpp
  intel_extension_for_transformers/llm/runtime/graph/core/parallel_context.h
  intel_extension_for_transformers/llm/runtime/graph/models/bloom/bloom.cpp
  intel_extension_for_transformers/llm/runtime/graph/models/chatglm/chatglm1.cpp
  intel_extension_for_transformers/llm/runtime/graph/models/chatglm/chatglm1_utils.cpp
  intel_extension_for_transformers/llm/runtime/graph/models/chatglm/chatglm2.cpp
  intel_extension_for_transformers/llm/runtime/graph/models/chatglm/chatglm2.h
  intel_extension_for_transformers/llm/runtime/graph/models/chatglm/chatglm2_utils.cpp
  intel_extension_for_transformers/llm/runtime/graph/models/falcon/falcon.cpp
  intel_extension_for_transformers/llm/runtime/graph/models/gptj/gptj.cpp
  intel_extension_for_transformers/llm/runtime/graph/models/gptneox/gptneox.cpp
  intel_extension_for_transformers/llm/runtime/graph/models/model_utils/arg_parse.cpp
  intel_extension_for_transformers/llm/runtime/graph/models/model_utils/model_files.h
  intel_extension_for_transformers/llm/runtime/graph/models/model_utils/model_types.h
  intel_extension_for_transformers/llm/runtime/graph/models/model_utils/quant_config.h
  intel_extension_for_transformers/llm/runtime/graph/models/mpt/mpt.cpp
  intel_extension_for_transformers/llm/runtime/graph/models/starcoder/starcoder.cpp
Labels: ITREX v1.2

#203 add one-click script for cpp graph running
  intel_extension_for_transformers/llm/runtime/graph/README.md
  intel_extension_for_transformers/llm/runtime/graph/scripts/one_click_run.py
Labels: ITREX v1.2

#257 Refine mpt text-generation example
  examples/huggingface/pytorch/text-generation/quantization/README.md
  examples/huggingface/pytorch/text-generation/quantization/requirements.txt
  examples/huggingface/pytorch/text-generation/quantization/run_generation.py
  requirements.txt
Labels: ITREX v1.2

#239 fix3rdparty--rebase
  docker/Dockerfile
  intel_extension_for_transformers/llm/runtime/deprecated/executor/src/i_malloc.cpp
  workflows/chatbot/demo/basic_frontend/fastchat/eval/webpage/index.html
  workflows/chatbot/demo/docker/Dockerfile
  workflows/chatbot/inference/backend/chat/tts.py
  workflows/chatbot/inference/backend/fastrag/fastrag_service.py
Labels: ITREX v1.2

#271 Q4 perchannel
  intel_extension_for_transformers/llm/library/jblas/jblas/jit_blas_utils.h
  intel_extension_for_transformers/llm/library/jblas/jblas/jit_blas_weight_compression.h
  intel_extension_for_transformers/llm/library/jblas/jblas/kernel_ref.h
  intel_extension_for_transformers/llm/library/jblas/jblas/kernel_wrapper.h
  intel_extension_for_transformers/llm/runtime/graph/core/layers/inner_product.cpp
  intel_extension_for_transformers/llm/runtime/graph/core/layers/ip_fusion_ffn.cpp
  intel_extension_for_transformers/llm/runtime/graph/core/layers/ip_fusion_qkv.cpp
  intel_extension_for_transformers/llm/runtime/graph/core/layers/jblas_common.hpp
  intel_extension_for_transformers/llm/runtime/graph/core/ne_layers.c
  intel_extension_for_transformers/llm/runtime/graph/models/model_utils/model_utils.cpp
Labels: ITREX v1.2

#273 update pylint and cpp graph
  .github/workflows/cpp-graph-test.yml
  .github/workflows/script/formatScan/pylint.sh
  .github/workflows/script/models/cpp_graph_inference.sh
  intel_extension_for_transformers/transformers/modeling/modeling_base_seq2seq.py
  workflows/chatbot/inference/backend/fastrag/fastrag_service.py
Labels: ITREX v1.2

#256 Add TTS finetuning interface
  intel_extension_for_transformers/neural_chat/config.py
  intel_extension_for_transformers/neural_chat/pipeline/plugins/audio/finetuning/tts_finetuning.py
Labels: ITREX v1.2, demo

#238 rename configs for woq
  examples/huggingface/pytorch/language-modeling/quantization/README.md
  examples/huggingface/pytorch/language-modeling/quantization/run_clm_no_trainer.py
  examples/huggingface/pytorch/language-modeling/quantization/run_tuning.sh
  intel_extension_for_transformers/llm/quantization/optimization.py
  intel_extension_for_transformers/neural_chat/config.py
Labels: WIP, ITREX v1.2

#196 Update inference.py and generate.py in NeuralChat
  intel_extension_for_transformers/llm/inference/inference.py
  workflows/chatbot/inference/README.md
  workflows/chatbot/inference/generate.py
Labels: ITREX v1.2

#111 Update dockerfile and README for chatbot demo
  workflows/chatbot/demo/docker/Dockerfile
  workflows/chatbot/demo/docker/README.md
  workflows/chatbot/inference/backend/chat/controller.py
  workflows/chatbot/inference/backend/chat/model_worker.py
  workflows/chatbot/inference/backend/chat/run_ipex.sh
  workflows/chatbot/inference/backend/fastrag/fastrag_service.py
  workflows/chatbot/inference/backend/llmcache/cache.py
Labels: ITREX v1.2

#285 [CPP Graph] Fix q4_0 gptj with MHA fusion enabled
  intel_extension_for_transformers/llm/runtime/graph/application/main_run.cpp
  intel_extension_for_transformers/llm/runtime/graph/models/gptj/gptj.cpp
  intel_extension_for_transformers/llm/runtime/graph/models/llama/llama.cpp
Labels: ITREX.cpp

#289 [CPP Graph] Fix q4_0 gptj with MHA fusion enabled
  intel_extension_for_transformers/llm/runtime/graph/application/main_run.cpp
  intel_extension_for_transformers/llm/runtime/graph/models/gptj/gptj.cpp
  intel_extension_for_transformers/llm/runtime/graph/models/llama/llama.cpp
Labels: ITREX.cpp, ITREX v1.2

#280 support avx2 prologue
  intel_extension_for_transformers/llm/library/jblas/jblas/jit_blas_gemm.h
  intel_extension_for_transformers/llm/library/jblas/jblas/jit_blas_utils.h
  intel_extension_for_transformers/llm/library/jblas/jblas/kernel_avx2.h
  intel_extension_for_transformers/llm/library/jblas/jblas/kernel_avx512f.h
  intel_extension_for_transformers/llm/library/jblas/jblas/kernel_ref.h
  intel_extension_for_transformers/llm/library/jblas/jblas/kernel_wrapper.h
Labels: ITREX.cpp

#284 fix the bloom and dolly ffn fusion error
  intel_extension_for_transformers/llm/runtime/graph/CMakeLists.txt
  intel_extension_for_transformers/llm/runtime/graph/application/main_run.cpp
  intel_extension_for_transformers/llm/runtime/graph/models/bloom/bloom.cpp
  intel_extension_for_transformers/llm/runtime/graph/models/gptneox/gptneox.cpp
Labels: ITREX.cpp

#278 [CPP Graph] ChatGLM Enabling and ChatGLM-2 Issues Fix
  intel_extension_for_transformers/llm/runtime/graph/README.md
  intel_extension_for_transformers/llm/runtime/graph/application/CMakeLists.txt
  intel_extension_for_transformers/llm/runtime/graph/application/common.cpp
  intel_extension_for_transformers/llm/runtime/graph/application/common.h
  intel_extension_for_transformers/llm/runtime/graph/application/main_run.cpp
  intel_extension_for_transformers/llm/runtime/graph/core/ne_layers.c
  intel_extension_for_transformers/llm/runtime/graph/core/ne_layers.h
  intel_extension_for_transformers/llm/runtime/graph/models/chatglm/CMakeLists.txt
  intel_extension_for_transformers/llm/runtime/graph/models/chatglm/chatglm.cpp
  intel_extension_for_transformers/llm/runtime/graph/models/chatglm/chatglm.h
  intel_extension_for_transformers/llm/runtime/graph/models/chatglm/chatglm2.cpp
  intel_extension_for_transformers/llm/runtime/graph/models/chatglm/chatglm2.h
  intel_extension_for_transformers/llm/runtime/graph/models/chatglm/chatglm_utils.cpp
  intel_extension_for_transformers/llm/runtime/graph/models/model_utils/arg_parse.cpp
  intel_extension_for_transformers/llm/runtime/graph/models/model_utils/model_files.h
  intel_extension_for_transformers/llm/runtime/graph/models/model_utils/model_types.h
  intel_extension_for_transformers/llm/runtime/graph/scripts/convert_bloom.py
  intel_extension_for_transformers/llm/runtime/graph/scripts/convert_chatglm.py
  intel_extension_for_transformers/llm/runtime/graph/scripts/convert_dolly.py
  intel_extension_for_transformers/llm/runtime/graph/scripts/convert_falcon.py
  intel_extension_for_transformers/llm/runtime/graph/scripts/convert_gptj.py
  intel_extension_for_transformers/llm/runtime/graph/scripts/convert_gptneox.py
  intel_extension_for_transformers/llm/runtime/graph/scripts/convert_llama.py
  intel_extension_for_transformers/llm/runtime/graph/scripts/convert_model.py
  intel_extension_for_transformers/llm/runtime/graph/scripts/convert_mpt.py
  intel_extension_for_transformers/llm/runtime/graph/scripts/convert_opt.py
  intel_extension_for_transformers/llm/runtime/graph/scripts/convert_starcoder.py
  intel_extension_for_transformers/llm/runtime/graph/scripts/run_llm.py
Labels: ITREX.cpp

#312 [Graph] windows build
  intel_extension_for_transformers/llm/runtime/graph/README.md
  intel_extension_for_transformers/llm/runtime/graph/application/common.h
  intel_extension_for_transformers/llm/runtime/graph/core/layers/mha_dense.cpp
  intel_extension_for_transformers/llm/runtime/graph/models/chatglm/chatglm2_utils.cpp
Labels: ITREX.cpp

#306 [CPP Graph] Asym model
  .github/workflows/script/models/cpp_graph_inference.sh
  intel_extension_for_transformers/llm/library/jblas/jblas/jit_blas_weight_compression.h
  intel_extension_for_transformers/llm/runtime/graph/models/model_utils/model_files.h
  intel_extension_for_transformers/llm/runtime/graph/models/model_utils/model_utils.cpp
Labels: ITREX.cpp

#329 Refine NeuralChat notebook
  intel_extension_for_transformers/neural_chat/README.md
  intel_extension_for_transformers/neural_chat/docs/full_notebooks.md
Labels: ITREX v1.2

#327 fix position_ids issue, add lm_eval
  examples/huggingface/pytorch/language-modeling/pruning/README.md
  examples/huggingface/pytorch/language-modeling/pruning/requirements.txt
  examples/huggingface/pytorch/language-modeling/pruning/run_clm_sparsegpt.py
  intel_extension_for_transformers/transformers/modeling/gptj/modeling_gptj.py
  intel_extension_for_transformers/transformers/modeling/llama/modeling_llama.py
Labels: documentation, draft, ITREX v1.2

#326 fix the dolly failed
  examples/huggingface/pytorch/text-generation/deployment/generation_utils.py
Labels: bug, ITREX v1.2

#315 Refactored inference API, and extracted prompt template as individual module
  intel_extension_for_transformers/llm/utils/__init__.py
  intel_extension_for_transformers/llm/utils/mpt_trace.py
  intel_extension_for_transformers/neural_chat/chatbot.py
  intel_extension_for_transformers/neural_chat/models/base_model.py
  intel_extension_for_transformers/neural_chat/models/model_utils.py
  intel_extension_for_transformers/neural_chat/pipeline/plugins/retrieval/detector/intent_detection.py
  intel_extension_for_transformers/neural_chat/prompts/__init__.py
  intel_extension_for_transformers/neural_chat/prompts/prompt.py
  intel_extension_for_transformers/neural_chat/tests/optimization/test_optimization.py
Labels: ITREX v1.2

#336 fix checkmarx issue
  intel_extension_for_transformers/neural_chat/examples/tts_finetuning/inference.py
  intel_extension_for_transformers/neural_chat/pipeline/plugins/audio/utils/cut_video.py
  intel_extension_for_transformers/neural_chat/pipeline/plugins/audio/utils/video_to_wav.py
  setup.py
Labels: bug, ITREX v1.2

#321 add ut for checking the accuracy of the RAG to avoid the other changes influence the retrieval and the generation result
  intel_extension_for_transformers/neural_chat/assets/docs/sample.txt
  intel_extension_for_transformers/neural_chat/pipeline/plugins/retrieval/indexing/context_utils.py
  intel_extension_for_transformers/neural_chat/tests/api/test_inference.py
  intel_extension_for_transformers/neural_chat/tests/api/test_rag.py
Labels: ITREX v1.2

#345 update text-generation scripts
  examples/.config/pytorch_optimize.json
  examples/huggingface/pytorch/text-generation/quantization/build_env.sh
  examples/huggingface/pytorch/text-generation/quantization/run_benchmark.sh
  examples/huggingface/pytorch/text-generation/quantization/run_tuning.sh
Labels: ITREX v1.2

#343 New avx512_vnni kernel
  intel_extension_for_transformers/llm/library/jblas/jblas/jit_base.hpp
  intel_extension_for_transformers/llm/library/jblas/jblas/jit_blas.h
  intel_extension_for_transformers/llm/library/jblas/jblas/jit_blas_gemm.h
  intel_extension_for_transformers/llm/library/jblas/jblas/jit_blas_utils.h
  intel_extension_for_transformers/llm/library/jblas/jblas/jit_blas_weight_compression.h
  intel_extension_for_transformers/llm/library/jblas/jblas/jit_blas_wrapper.h
  intel_extension_for_transformers/llm/library/jblas/jblas/kernel_avx2.h
  intel_extension_for_transformers/llm/library/jblas/jblas/kernel_avx512_bf16.h
  intel_extension_for_transformers/llm/library/jblas/jblas/kernel_avx512f.h
  intel_extension_for_transformers/llm/library/jblas/jblas/kernel_ref.h
  intel_extension_for_transformers/llm/library/jblas/jblas/kernel_wrapper.h
  intel_extension_for_transformers/llm/operator/cscr/dispatcher/src/jblas_weightonly_dispatcher.cpp
  intel_extension_for_transformers/llm/operator/cscr/qbits_ut/weightonly_test.py
  intel_extension_for_transformers/llm/runtime/graph/core/layers/inner_product.cpp
  intel_extension_for_transformers/llm/runtime/graph/core/layers/ip_fusion_ffn.cpp
  intel_extension_for_transformers/llm/runtime/graph/core/layers/ip_fusion_qkv.cpp
  intel_extension_for_transformers/llm/runtime/graph/core/layers/jblas_common.hpp
Labels: ITREX.cpp

#320 Refine Script and args for Cpp Graph
  .github/workflows/script/models/cpp_graph_inference.sh
  intel_extension_for_transformers/llm/quantization/utils.py
  intel_extension_for_transformers/llm/runtime/graph/README.md
  intel_extension_for_transformers/llm/runtime/graph/__init__.py
  intel_extension_for_transformers/llm/runtime/graph/application/common.cpp
  intel_extension_for_transformers/llm/runtime/graph/application/common.h
  intel_extension_for_transformers/llm/runtime/graph/application/main_pybind.cpp
  intel_extension_for_transformers/llm/runtime/graph/models/model_utils/model_utils.cpp
  intel_extension_for_transformers/llm/runtime/graph/models/model_utils/quant_config.h
  intel_extension_for_transformers/llm/runtime/graph/scripts/convert.py
  intel_extension_for_transformers/llm/runtime/graph/scripts/inference.py
  intel_extension_for_transformers/llm/runtime/graph/scripts/one_click_run.py
  intel_extension_for_transformers/llm/runtime/graph/scripts/quantize.py
  intel_extension_for_transformers/llm/runtime/graph/tensor_parallelism.md
  intel_extension_for_transformers/transformers/modeling/modeling_auto.py
Labels: ITREX.cpp, ITREX v1.2

#353 Fixed error for replace -100s in predictions by the pad token
  examples/huggingface/pytorch/summarization/quantization/run_summarization.py
  intel_extension_for_transformers/transformers/modeling/modeling_auto.py
Labels: ITREX v1.2

#346 Jupyter notebook and example for setting up an end to end text chatbot
  intel_extension_for_transformers/neural_chat/docs/full_notebooks.md
  intel_extension_for_transformers/neural_chat/docs/notebooks/setup_text_chatbot_service_on_spr.ipynb
  intel_extension_for_transformers/neural_chat/docs/tutorial.md
  intel_extension_for_transformers/neural_chat/examples/textbot/README.md
  intel_extension_for_transformers/neural_chat/examples/textbot/backend/README.md
  intel_extension_for_transformers/neural_chat/examples/textbot/backend/run.sh
  intel_extension_for_transformers/neural_chat/examples/textbot/backend/run_text_chat.py
  intel_extension_for_transformers/neural_chat/examples/textbot/backend/textbot.yaml
  intel_extension_for_transformers/neural_chat/examples/textbot/frontend
  intel_extension_for_transformers/neural_chat/requirements.txt
  intel_extension_for_transformers/neural_chat/requirements_cpu.txt
  intel_extension_for_transformers/neural_chat/server/README.md
  intel_extension_for_transformers/neural_chat/server/restful/textchat_api.py
  intel_extension_for_transformers/neural_chat/ui/textbot/README.md
  intel_extension_for_transformers/neural_chat/ui/textbot/app.py
  intel_extension_for_transformers/neural_chat/ui/textbot/fastchat/conversation.py
Labels: ITREX v1.2

#350 Restrict onnxruntime version
  intel_extension_for_transformers/llm/runtime/deprecated/test/pytest/test_text_encoder.py
  intel_extension_for_transformers/llm/runtime/deprecated/test/pytest/test_text_encoder_bf16.py
  intel_extension_for_transformers/llm/runtime/deprecated/test/pytest/test_unet.py
  intel_extension_for_transformers/llm/runtime/deprecated/test/pytest/test_unet_qat.py
  intel_extension_for_transformers/llm/runtime/deprecated/test/pytest/test_vae_decoder.py
  intel_extension_for_transformers/llm/runtime/deprecated/test/pytest/test_vae_decoder_bf16.py
  tests/requirements.txt
Labels: ITREX v1.2

#354 Support load_in_4bit and load_in_8bit on CPU device
  examples/.config/pytorch_optimize.json
  examples/huggingface/pytorch/text-generation/quantization/README.md
  examples/huggingface/pytorch/text-generation/quantization/run_benchmark.sh
  examples/huggingface/pytorch/text-generation/quantization/run_generation.py
  examples/huggingface/pytorch/text-generation/quantization/run_tuning.sh
  intel_extension_for_transformers/llm/quantization/utils.py
  intel_extension_for_transformers/transformers/modeling/modeling_auto.py
  intel_extension_for_transformers/transformers/utils/quantization_config.py
  tests/test_quantization.py
Labels: extension

#264 Migrated finetuning and inference code of workflow chatbot to use NeuralChat API
  .github/workflows/chatbot-finetune-mpt-7b-chat-hpu.yml
  .github/workflows/chatbot-finetune-mpt-7b-chat.yml
  .github/workflows/chatbot-inference-llama-2-7b-chat-hf-hpu.yml
  .github/workflows/chatbot-inference-llama-2-7b-chat-hf.yml
  .github/workflows/chatbot-inference-mpt-7b-chat-hpu.yml
  .github/workflows/chatbot-inference-mpt-7b-chat.yml
  .github/workflows/script/chatbot/prepare_ft_mpt-7b-chat_mpi.sh
  .github/workflows/script/chatbot/start_ft_mpt-7b-chat_mpi.sh
  intel_extension_for_transformers/llm/finetuning/finetuning.py
  intel_extension_for_transformers/neural_chat/config.py
  intel_extension_for_transformers/neural_chat/docker/Dockerfile
  intel_extension_for_transformers/neural_chat/examples/instruction_tuning/README.md
  workflows/chatbot/fine_tuning/README.md
  workflows/chatbot/fine_tuning/docker/Dockerfile
  workflows/chatbot/fine_tuning/docker/README.md
  workflows/chatbot/fine_tuning/instruction_tuning_pipeline/data_utils.py
  workflows/chatbot/fine_tuning/instruction_tuning_pipeline/eval_utils.py
  workflows/chatbot/fine_tuning/instruction_tuning_pipeline/finetune_clm.py
  workflows/chatbot/fine_tuning/instruction_tuning_pipeline/finetune_seq2seq.py
  workflows/chatbot/inference/checkpoint_utils.py
  workflows/chatbot/inference/docker/0001-fix-lm-head-overriden-issue-move-it-from-checkpoint-.patch
  workflows/chatbot/inference/docker/Dockerfile
  workflows/chatbot/inference/docker/README.md
  workflows/chatbot/inference/generate.py
Labels: draft, ITREX v1.2, demo

#375 Add an end to end talkingbot example and notebook
  intel_extension_for_transformers/neural_chat/docs/notebooks/setup_talking_chatbot_service_on_spr.ipynb
  intel_extension_for_transformers/neural_chat/examples/talkingbot/README.md
  intel_extension_for_transformers/neural_chat/examples/talkingbot/backend/README.md
  intel_extension_for_transformers/neural_chat/examples/talkingbot/backend/run.sh
  intel_extension_for_transformers/neural_chat/examples/talkingbot/backend/talkingbot.py
  intel_extension_for_transformers/neural_chat/examples/talkingbot/backend/talkingbot.yaml
  intel_extension_for_transformers/neural_chat/examples/talkingbot/frontend
  intel_extension_for_transformers/neural_chat/models/base_model.py
  intel_extension_for_transformers/neural_chat/pipeline/plugins/audio/tts.py
  intel_extension_for_transformers/neural_chat/server/neuralchat_client.py
  intel_extension_for_transformers/neural_chat/server/restful/voicechat_api.py
  intel_extension_for_transformers/neural_chat/tests/server/test_voicechat_server.py
  intel_extension_for_transformers/neural_chat/tests/server/voicechat.yaml
Labels: ITREX v1.2

#369 [CPP Graph] KV-Update Optimization
  intel_extension_for_transformers/llm/library/jblas/jblas/jit_base.hpp
  intel_extension_for_transformers/llm/library/jblas/jblas/jit_blas_transformer.h
  intel_extension_for_transformers/llm/library/jblas/jblas/jit_blas_utils.h
  intel_extension_for_transformers/llm/library/jblas/jblas/jit_blas_weight_compression.h
  intel_extension_for_transformers/llm/library/jblas/jblas/jit_blas_wrapper.h
  intel_extension_for_transformers/llm/library/jblas/jblas/kernel_avx2.h
  intel_extension_for_transformers/llm/library/jblas/jblas/kernel_jit.h
  intel_extension_for_transformers/llm/runtime/graph/core/layers/mha_dense.cpp
  intel_extension_for_transformers/llm/runtime/graph/core/ne.h
  intel_extension_for_transformers/llm/runtime/graph/models/model_utils/model_utils.cpp
Labels: ITREX v1.2, extension

#387 refine sparseGPT example & scripts
  examples/huggingface/pytorch/language-modeling/pruning/README.md
  examples/huggingface/pytorch/language-modeling/pruning/run_clm_sparsegpt.py
  examples/huggingface/pytorch/language-modeling/pruning/scripts/run_llm_sparseGPT.sh
Labels: ITREX v1.2

#382 fix python api bug
  intel_extension_for_transformers/llm/runtime/graph/__init__.py
  intel_extension_for_transformers/transformers/modeling/modeling_auto.py
Labels: ITREX v1.2

#213 [CPP Graph] Enable llama2-70b
  intel_extension_for_transformers/llm/runtime/graph/README.md
  intel_extension_for_transformers/llm/runtime/graph/models/llama/llama.cpp
  intel_extension_for_transformers/llm/runtime/graph/models/llama/llama.h
  intel_extension_for_transformers/llm/runtime/graph/models/llama/llama_utils.cpp
  intel_extension_for_transformers/llm/runtime/graph/models/model_utils/model_utils.cpp
  intel_extension_for_transformers/llm/runtime/graph/scripts/convert_llama.py
Labels: WIP, ITREX.cpp

#386 add readme for llm kernels
  intel_extension_for_transformers/llm/runtime/graph/README.md
  intel_extension_for_transformers/llm/runtime/graph/core/README.md
Labels: ITREX v1.2

#391 Update README.md for llama2 70B
  intel_extension_for_transformers/llm/runtime/graph/README.md
Labels: ITREX v1.2

#377 add talkingbot-pc code
  intel_extension_for_transformers/neural_chat/examples/talkingbot_pc/build_talkingbot_on_pc.ipynb
  intel_extension_for_transformers/neural_chat/pipeline/plugins/audio/tts.py
  intel_extension_for_transformers/neural_chat/requirements_pc.txt
Labels: ITREX v1.2

#392 add notebook entry
  intel_extension_for_transformers/neural_chat/docs/full_notebooks.md
Labels: ITREX v1.2

#393 Refine Chatbot readme
  intel_extension_for_transformers/neural_chat/README.md
Labels: ITREX v1.2

#366 add dpo code.
  intel_extension_for_transformers/transformers/dpo_trainer.py
  tests/test_dpo.py
  workflows/chatbot/fine_tuning/dpo_pipeline/README.md
  workflows/chatbot/fine_tuning/dpo_pipeline/dpo_clm.py
  workflows/chatbot/fine_tuning/dpo_pipeline/requirements.txt
Labels: ITREX v1.2

#358 enable the user to load the local database to avoid unnecessary data preprocessing
  intel_extension_for_transformers/neural_chat/pipeline/plugins/retrieval/README.md
  intel_extension_for_transformers/neural_chat/pipeline/plugins/retrieval/indexing/indexing.py
  intel_extension_for_transformers/neural_chat/pipeline/plugins/retrieval/retrieval_agent.py
  intel_extension_for_transformers/neural_chat/tests/api/test_inference.py
  intel_extension_for_transformers/neural_chat/tests/api/test_rag.py
Labels: draft, ITREX v1.2

#396 remove denpendency of fairscale.
  workflows/chatbot/fine_tuning/dpo_pipeline/requirements.txt
Labels: ITREX v1.2

#395 Refine LLM runtime readme
  intel_extension_for_transformers/llm/runtime/graph/README.md
Labels: ITREX v1.2

#388 Use transfomers tokenizer and streamer for python api
  README.md
  intel_extension_for_transformers/llm/runtime/graph/README.md
  intel_extension_for_transformers/llm/runtime/graph/__init__.py
  intel_extension_for_transformers/llm/runtime/graph/application/main_pybind.cpp
  intel_extension_for_transformers/llm/runtime/graph/scripts/python_api_example.py
  intel_extension_for_transformers/neural_chat/examples/talkingbot_pc/build_talkingbot_on_pc.ipynb
  intel_extension_for_transformers/transformers/modeling/modeling_auto.py
  intel_extension_for_transformers/transformers/utils/quantization_config.py
  setup.py
  tests/test_llm_runtime.py
Labels: ITREX v1.2

#397 Fix double import issue and update pip install itrex
  intel_extension_for_transformers/neural_chat/docs/notebooks/amp_optimization_on_spr.ipynb
  intel_extension_for_transformers/neural_chat/docs/notebooks/build_chatbot_on_icx.ipynb
  intel_extension_for_transformers/neural_chat/docs/notebooks/build_chatbot_on_nv_a100.ipynb
  intel_extension_for_transformers/neural_chat/docs/notebooks/build_chatbot_on_spr.ipynb
  intel_extension_for_transformers/neural_chat/docs/notebooks/build_chatbot_on_xpu.ipynb
  intel_extension_for_transformers/neural_chat/docs/notebooks/customize_chatbot_with_finetuned_models.ipynb
  intel_extension_for_transformers/neural_chat/docs/notebooks/customize_chatbot_with_optimized_models.ipynb
  intel_extension_for_transformers/neural_chat/docs/notebooks/deploy_chatbot_on_icx.ipynb
  intel_extension_for_transformers/neural_chat/docs/notebooks/deploy_chatbot_on_nv_a100.ipynb
  intel_extension_for_transformers/neural_chat/docs/notebooks/deploy_chatbot_on_spr.ipynb
  intel_extension_for_transformers/neural_chat/docs/notebooks/deploy_chatbot_on_xpu.ipynb
  intel_extension_for_transformers/neural_chat/docs/notebooks/finetuning_on_nv_a100.ipynb
  intel_extension_for_transformers/neural_chat/docs/notebooks/setup_talking_chatbot_service_on_spr.ipynb
  intel_extension_for_transformers/neural_chat/docs/notebooks/setup_text_chatbot_service_on_spr.ipynb
  intel_extension_for_transformers/neural_chat/docs/notebooks/single_node_finetuning_on_spr.ipynb
  intel_extension_for_transformers/neural_chat/docs/notebooks/weight_only_optimization_on_nv_a100.ipynb
  intel_extension_for_transformers/neural_chat/models/neuralchat_model.py
Labels: ITREX v1.2

#398 Enable build_chatbot_on_xpu.ipynb
  intel_extension_for_transformers/neural_chat/docs/notebooks/build_chatbot_on_xpu.ipynb
  intel_extension_for_transformers/neural_chat/docs/notebooks/deploy_chatbot_on_xpu.ipynb
  intel_extension_for_transformers/neural_chat/requirements.txt
  intel_extension_for_transformers/neural_chat/requirements_xpu.txt
  intel_extension_for_transformers/neural_chat/requirements_xpu_no_deps.txt
Labels: ITREX v1.2

#322 [Cpp Graph] Align Cpp Beam Search
  intel_extension_for_transformers/llm/runtime/graph/CMakeLists.txt
  intel_extension_for_transformers/llm/runtime/graph/application/pybind_gptj.cpp
  intel_extension_for_transformers/llm/runtime/graph/models/gptj/gptj.cpp
  intel_extension_for_transformers/llm/runtime/graph/models/model_utils/model_types.h
  intel_extension_for_transformers/llm/runtime/graph/models/model_utils/model_utils.cpp
  intel_extension_for_transformers/llm/runtime/graph/models/model_utils/model_utils.h
Labels: enhancement, draft, WIP, ITREX.cpp

#404 fix install from source
  README.md
  intel_extension_for_transformers/neural_chat/docker/Dockerfile
Labels: bug
