Repository intel/intel-extension-for-transformers, pull requests merged in 2023-12, with the labels that each got.

#833 Move `optimum` package import into export function
  intel_extension_for_transformers/transformers/trainer.py
Labels: bug, ITREX-1.3

#818 [LLM Runtime] Remove use_cache in WOQ
  intel_extension_for_transformers/llm/runtime/graph/README.md
  intel_extension_for_transformers/llm/runtime/graph/__init__.py
  intel_extension_for_transformers/llm/runtime/graph/tests/test_llm_runtime.py
  intel_extension_for_transformers/transformers/modeling/modeling_auto.py
  intel_extension_for_transformers/transformers/utils/quantization_config.py
Labels: ITREX.cpp, ITREX-1.3

#856 [LLM Runtime] Fix windows compile error
  intel_extension_for_transformers/llm/runtime/graph/core/ne_layers.c
Labels: bug, ITREX.cpp, ITREX-1.3

#863 Fix task infer bug in export
  intel_extension_for_transformers/transformers/trainer.py
  tests/CI/test_quantization.py
Labels: bug, ITREX-1.3

#891 [LLM Runtime] Baichuan13B inference bug fix
  intel_extension_for_transformers/llm/runtime/graph/README.md
  intel_extension_for_transformers/llm/runtime/graph/models/baichuan/baichuan.cpp
  intel_extension_for_transformers/llm/runtime/graph/scripts/convert_baichuan.py
Labels: ITREX.cpp, ready for merge

#895 improve reorder cache for the ipex.optimize_transformers.
  intel_extension_for_transformers/llm/evaluation/models.py
Labels: ITREX-1.3

#892 add constraint for peft
  intel_extension_for_transformers/neural_chat/requirements.txt
  intel_extension_for_transformers/neural_chat/requirements_cpu.txt
  intel_extension_for_transformers/neural_chat/requirements_hpu.txt
  intel_extension_for_transformers/neural_chat/requirements_xpu.txt
  intel_extension_for_transformers/neural_chat/tests/requirements.txt
Labels: ITREX-1.3

#752 [Infra] use python logging
  intel_extension_for_transformers/neural_chat/chatbot.py
  intel_extension_for_transformers/neural_chat/cli/cli_commands.py
  intel_extension_for_transformers/neural_chat/config_logging.py
  intel_extension_for_transformers/neural_chat/examples/finetuning/tts/asr.py
  intel_extension_for_transformers/neural_chat/examples/finetuning/tts/inference.py
  intel_extension_for_transformers/neural_chat/examples/plugins/retrieval/retrieval_chat.py
  intel_extension_for_transformers/neural_chat/models/base_model.py
  intel_extension_for_transformers/neural_chat/models/model_utils.py
  intel_extension_for_transformers/neural_chat/pipeline/plugins/audio/asr.py
  intel_extension_for_transformers/neural_chat/pipeline/plugins/audio/tts.py
  intel_extension_for_transformers/neural_chat/pipeline/plugins/audio/utils/cut_video.py
  intel_extension_for_transformers/neural_chat/pipeline/plugins/audio/utils/english_normalizer.py
  intel_extension_for_transformers/neural_chat/pipeline/plugins/audio/utils/reduce_noise.py
  intel_extension_for_transformers/neural_chat/pipeline/plugins/audio/utils/split_audio.py
  intel_extension_for_transformers/neural_chat/pipeline/plugins/audio/utils/video_to_wav.py
  intel_extension_for_transformers/neural_chat/pipeline/plugins/ner/ner.py
  intel_extension_for_transformers/neural_chat/pipeline/plugins/ner/ner_int.py
  intel_extension_for_transformers/neural_chat/pipeline/plugins/retrieval/indexing/html_parser.py
  intel_extension_for_transformers/neural_chat/pipeline/plugins/retrieval/indexing/indexing.py
  intel_extension_for_transformers/neural_chat/pipeline/plugins/retrieval/retrieval_agent.py
  intel_extension_for_transformers/neural_chat/pipeline/plugins/retrieval/retrieval_base.py
  intel_extension_for_transformers/neural_chat/pipeline/plugins/security/safety_checker.py
  intel_extension_for_transformers/neural_chat/pipeline/plugins/video/face_animation/inference.py
  intel_extension_for_transformers/neural_chat/pipeline/plugins/video/face_animation/sadtalker.py
Labels: enhancement, ITREX-1.3

#897 fix gradient issue for qlora on seq2seq
  intel_extension_for_transformers/llm/finetuning/finetuning.py
Labels: ITREX-1.3

#885 [NeuralChat] Update README for OpenAI-Compatible RESTful API
  intel_extension_for_transformers/neural_chat/README.md
  intel_extension_for_transformers/neural_chat/docs/neuralchat_api.md
Labels: ITREX-1.3

#894 [LLM Runtime] Remove the identical branch
  examples/huggingface/pytorch/text-classification/deployment/emotion/distilbert_base_uncased/executor_utils.py
  intel_extension_for_transformers/llm/runtime/deprecated/compile/sub_graph/qkv_merge.py
  intel_extension_for_transformers/llm/runtime/graph/scripts/convert_gptq_bloom.py
Labels: ITREX.cpp, ITREX-1.3

#884 add peft model support in deepspeed sharded mode
  intel_extension_for_transformers/neural_chat/models/model_utils.py
  workflows/chatbot/inference/README.md
Labels: ITREX-1.3

#903 [LLM Runtime] make rms_norm_eps and freq_base as parameter
  intel_extension_for_transformers/llm/runtime/graph/core/ne_layers.c
  intel_extension_for_transformers/llm/runtime/graph/core/ne_layers.h
  intel_extension_for_transformers/llm/runtime/graph/models/baichuan/baichuan.cpp
  intel_extension_for_transformers/llm/runtime/graph/models/chatglm/chatglm.cpp
  intel_extension_for_transformers/llm/runtime/graph/models/chatglm/chatglm2.cpp
  intel_extension_for_transformers/llm/runtime/graph/models/falcon/falcon.cpp
  intel_extension_for_transformers/llm/runtime/graph/models/gptj/gptj.cpp
  intel_extension_for_transformers/llm/runtime/graph/models/gptneox/gptneox.cpp
  intel_extension_for_transformers/llm/runtime/graph/models/llama/llama.cpp
  intel_extension_for_transformers/llm/runtime/graph/models/model_utils/model_files.h
  intel_extension_for_transformers/llm/runtime/graph/models/model_utils/model_types.h
  intel_extension_for_transformers/llm/runtime/graph/models/qwen/qwen.cpp
  intel_extension_for_transformers/llm/runtime/graph/scripts/convert_baichuan.py
  intel_extension_for_transformers/llm/runtime/graph/scripts/convert_bloom.py
  intel_extension_for_transformers/llm/runtime/graph/scripts/convert_chatglm.py
  intel_extension_for_transformers/llm/runtime/graph/scripts/convert_dolly.py
  intel_extension_for_transformers/llm/runtime/graph/scripts/convert_falcon.py
  intel_extension_for_transformers/llm/runtime/graph/scripts/convert_gptj.py
  intel_extension_for_transformers/llm/runtime/graph/scripts/convert_gptneox.py
  intel_extension_for_transformers/llm/runtime/graph/scripts/convert_gptq_bloom.py
  intel_extension_for_transformers/llm/runtime/graph/scripts/convert_llama.py
  intel_extension_for_transformers/llm/runtime/graph/scripts/convert_mistral.py
  intel_extension_for_transformers/llm/runtime/graph/scripts/convert_mpt.py
  intel_extension_for_transformers/llm/runtime/graph/scripts/convert_opt.py
  intel_extension_for_transformers/llm/runtime/graph/scripts/convert_qwen.py
  intel_extension_for_transformers/llm/runtime/graph/scripts/convert_starcoder.py
  intel_extension_for_transformers/transformers/modeling/modeling_auto.py
Labels: ITREX.cpp, ready for merge

#879 [NeuralChat] Support image to image plugin as service
  intel_extension_for_transformers/neural_chat/chatbot.py
  intel_extension_for_transformers/neural_chat/examples/deployment/plugin/audio/README.md
  intel_extension_for_transformers/neural_chat/examples/deployment/plugin/audio/audio_service.py
  intel_extension_for_transformers/neural_chat/examples/deployment/plugin/audio/audio_service.yaml
  intel_extension_for_transformers/neural_chat/examples/deployment/plugin/audio/run.sh
  intel_extension_for_transformers/neural_chat/examples/deployment/plugin/image2image/README.md
  intel_extension_for_transformers/neural_chat/examples/deployment/plugin/image2image/export_ir.py
  intel_extension_for_transformers/neural_chat/examples/deployment/plugin/image2image/export_model.sh
  intel_extension_for_transformers/neural_chat/examples/deployment/plugin/image2image/image2image_service.py
  intel_extension_for_transformers/neural_chat/examples/deployment/plugin/image2image/image2image_service.yaml
  intel_extension_for_transformers/neural_chat/examples/deployment/plugin/image2image/nohup.out
  intel_extension_for_transformers/neural_chat/examples/deployment/plugin/image2image/prepare_model.py
  intel_extension_for_transformers/neural_chat/examples/deployment/plugin/image2image/quantization_modules.py
  intel_extension_for_transformers/neural_chat/examples/deployment/plugin/image2image/requirements.txt
  intel_extension_for_transformers/neural_chat/examples/deployment/plugin/image2image/run.sh
  intel_extension_for_transformers/neural_chat/models/base_model.py
  intel_extension_for_transformers/neural_chat/pipeline/plugins/image2image/__init__.py
  intel_extension_for_transformers/neural_chat/pipeline/plugins/image2image/diffusion_utils.py
  intel_extension_for_transformers/neural_chat/pipeline/plugins/image2image/image2image.py
  intel_extension_for_transformers/neural_chat/pipeline/plugins/image2image/instructpix2pix_pipeline.py
  intel_extension_for_transformers/neural_chat/plugins.py
  intel_extension_for_transformers/neural_chat/requirements.txt
  intel_extension_for_transformers/neural_chat/server/neuralchat_server.py
  intel_extension_for_transformers/neural_chat/server/restful/api.py
  intel_extension_for_transformers/neural_chat/server/restful/plugin_image2image_api.py
  intel_extension_for_transformers/neural_chat/tests/requirements.txt
Labels: ITREX-1.3

#650 [NeuralChat] support return error code
  intel_extension_for_transformers/neural_chat/chatbot.py
  intel_extension_for_transformers/neural_chat/errorcode.py
  intel_extension_for_transformers/neural_chat/models/base_model.py
  intel_extension_for_transformers/neural_chat/models/model_utils.py
  intel_extension_for_transformers/neural_chat/tests/nightly/models/test_error_code.py
  intel_extension_for_transformers/neural_chat/utils/error_utils.py
  intel_extension_for_transformers/utils/logger.py
Labels: WIP, ITREX-1.3

#799 [Doc] add gaudi2 in doc
  .github/workflows/script/formatScan/nlp_dict.txt
  README.md
  docs/installation.md
  docs/release_data.md
  intel_extension_for_transformers/llm/runtime/graph/developer_document.md
Labels: documentation, ITREX-1.3

#934 Fix bug caused by sentense transformers upgrade
  intel_extension_for_transformers/langchain/embeddings/optimized_instructor_embedding.py
  intel_extension_for_transformers/langchain/embeddings/optimized_sentence_transformers.py
  intel_extension_for_transformers/neural_chat/tests/ci/api/test_chatbot_build_api.py
  intel_extension_for_transformers/neural_chat/tests/ci/api/test_inference.py
Labels: bug, NeuralChat

#872 [LLM Runtime] Add MX-Format (FP8_E5M2, FP8_E4M3, FP4_E2M1, NF4)
  .github/workflows/script/models/cpp_graph_inference.sh
  intel_extension_for_transformers/llm/runtime/graph/README.md
  intel_extension_for_transformers/llm/runtime/graph/__init__.py
  intel_extension_for_transformers/llm/runtime/graph/application/common.cpp
  intel_extension_for_transformers/llm/runtime/graph/application/common.h
  intel_extension_for_transformers/llm/runtime/graph/models/model_utils/model_utils.cpp
  intel_extension_for_transformers/llm/runtime/graph/models/model_utils/quant_config.h
  intel_extension_for_transformers/llm/runtime/graph/scripts/python_api_example.py
  intel_extension_for_transformers/llm/runtime/graph/scripts/quantize.py
  intel_extension_for_transformers/llm/runtime/graph/scripts/run.py
  intel_extension_for_transformers/transformers/modeling/modeling_auto.py
  intel_extension_for_transformers/transformers/utils/config.py
  tests/CI/test_weight_only.py
Labels: ITREX.cpp, ready for merge

#937 [LLM Runtime] Fix PPL Test
  intel_extension_for_transformers/llm/runtime/graph/application/main_pybind.cpp
  intel_extension_for_transformers/llm/runtime/graph/scripts/perplexity.py
Labels: ITREX.cpp, ITREX-1.3

#945 [LLM Runtime] Add MatMul data types combinations table
  intel_extension_for_transformers/llm/runtime/graph/README.md
  intel_extension_for_transformers/llm/runtime/graph/application/common.cpp
  intel_extension_for_transformers/llm/runtime/graph/application/common.h
  intel_extension_for_transformers/llm/runtime/graph/scripts/python_api_example.py
  intel_extension_for_transformers/llm/runtime/graph/scripts/quantize.py
  intel_extension_for_transformers/transformers/utils/config.py
Labels: ITREX.cpp, ITREX-1.3

#940 [LLM Runtime] decoupling weight_type and scale_type in Qbits
  .github/workflows/script/models/cpp_graph_inference.sh
  intel_extension_for_transformers/llm/library/jblas/jblas/jit_blas_prologue_a.h
  intel_extension_for_transformers/llm/library/jblas/jblas/jit_blas_prologue_b.h
  intel_extension_for_transformers/llm/library/jblas/jblas/jit_blas_storage.h
  intel_extension_for_transformers/llm/library/jblas/jblas/kernel_avx2.h
  intel_extension_for_transformers/llm/library/jblas/jblas/kernel_avx512f.h
  intel_extension_for_transformers/llm/library/jblas/jblas/kernel_ref.h
  intel_extension_for_transformers/llm/library/jblas/jblas/kernel_wrapper.h
  intel_extension_for_transformers/llm/operator/csrc/dispatcher/include/jblas_weightonly_dispatcher.hpp
  intel_extension_for_transformers/llm/operator/csrc/dispatcher/src/jblas_weightonly_dispatcher.cpp
  intel_extension_for_transformers/llm/operator/csrc/qbits.cpp
  intel_extension_for_transformers/llm/operator/csrc/qbits_ut/test_weightonly.py
  intel_extension_for_transformers/llm/quantization/autograd/functions.py
  intel_extension_for_transformers/llm/quantization/nn/modules.py
  intel_extension_for_transformers/llm/quantization/utils.py
  intel_extension_for_transformers/llm/runtime/graph/models/model_utils/model_utils.cpp
  intel_extension_for_transformers/llm/runtime/graph/scripts/python_api_example.py
  intel_extension_for_transformers/llm/runtime/graph/scripts/quantize.py
  intel_extension_for_transformers/transformers/utils/config.py
  tests/CI/test_quantization.py
  tests/CI/test_weight_only.py
Labels: ITREX.cpp, ready for merge, ITREX-1.3

#966 [LLM] Adapt models didn't need position ids do sq auto tune
  intel_extension_for_transformers/transformers/modeling/modeling_auto.py
  tests/CI/test_quantization.py
Labels: bug, ITREX-1.3

#964 [LLM Runtime] Fix mistral bf16
  intel_extension_for_transformers/llm/runtime/graph/scripts/convert_mistral.py
Labels: WIP

#969 [LLM Runtime]Improve Windows first token inference performance
  intel_extension_for_transformers/llm/runtime/graph/CMakeLists.txt
  intel_extension_for_transformers/llm/runtime/graph/cmake/ISA.cmake
Labels: ITREX.cpp, ready for merge, ITREX-1.3

#977 [Doc]refine example
  README.md
  intel_extension_for_transformers/llm/runtime/graph/README.md
Labels: ready for merge

#980 Fix ORT whisper example
  examples/huggingface/onnxruntime/speech-recognition/quantization/requirements.txt
Labels: bug, ITREX-1.3

#957 [NeuralChat] Specify local model path for nightly UT
  intel_extension_for_transformers/neural_chat/requirements.txt
  intel_extension_for_transformers/neural_chat/tests/nightly/models/test_chatglm.py
  intel_extension_for_transformers/neural_chat/tests/nightly/models/test_codellama.py
  intel_extension_for_transformers/neural_chat/tests/nightly/models/test_llama.py
  intel_extension_for_transformers/neural_chat/tests/nightly/models/test_mistral.py
  intel_extension_for_transformers/neural_chat/tests/nightly/models/test_model_utils.py
  intel_extension_for_transformers/neural_chat/tests/nightly/models/test_mpt.py
  intel_extension_for_transformers/neural_chat/tests/nightly/models/test_neuralchat.py
  intel_extension_for_transformers/neural_chat/tests/nightly/models/test_qwen.py
  intel_extension_for_transformers/neural_chat/tests/nightly/models/test_starcoder.py
  intel_extension_for_transformers/neural_chat/tests/requirements.txt
Labels: ITREX-1.3

#975 [NeuralChat] Fix UT issues on Habana
  intel_extension_for_transformers/neural_chat/tests/ci/api/test_chatbot_build_api.py
  intel_extension_for_transformers/neural_chat/tests/ci/api/test_chatbot_normal.py
  intel_extension_for_transformers/neural_chat/tests/ci/api/test_inference.py
  intel_extension_for_transformers/neural_chat/tests/ci/api/test_rag.py
  intel_extension_for_transformers/neural_chat/tests/nightly/models/test_neuralchat.py
  intel_extension_for_transformers/neural_chat/tests/nightly/plugins/video/test_sadtalker.py
Labels: ITREX-1.3

#976 Fix embeddings to support local file
  intel_extension_for_transformers/langchain/embeddings/optimized_instructor_embedding.py
  intel_extension_for_transformers/langchain/embeddings/optimized_sentence_transformers.py
  intel_extension_for_transformers/langchain/embeddings/utils.py
  intel_extension_for_transformers/neural_chat/tests/ci/api/test_chatbot_build_api.py
Labels: bug, ITREX-1.3

#955 [LLM] Fix llm models extension issue
  examples/huggingface/pytorch/code-generation/quantization/README.md
  examples/huggingface/pytorch/code-generation/quantization/requirements.txt
  examples/huggingface/pytorch/code-generation/quantization/run_generation.py
  examples/huggingface/pytorch/text-generation/quantization/requirements.txt
  examples/huggingface/pytorch/text-generation/quantization/run_benchmark.sh
  examples/huggingface/pytorch/text-generation/quantization/run_generation.py
  examples/huggingface/pytorch/text-generation/quantization/run_tuning.sh
  intel_extension_for_transformers/llm/evaluation/lm_eval/models/huggingface.py
  intel_extension_for_transformers/llm/evaluation/models.py
  intel_extension_for_transformers/transformers/modeling/modeling_auto.py
  intel_extension_for_transformers/transformers/utils/utility.py
Labels: ITREX-1.3

#946 Fixed issue for T5 base model quantization issue with IPEX smoothquant
  examples/.config/pytorch_optimize.json
  examples/huggingface/pytorch/text2text-generation/requirements.txt
  examples/huggingface/pytorch/text2text-generation/run_benchmark.sh
  examples/huggingface/pytorch/text2text-generation/run_seq2seq_generation.py
  examples/huggingface/pytorch/text2text-generation/run_tuning.sh
Labels: bug, ITREX-1.3

#1057 [LLM Runtime] Fix the accuracy issue with group_size=-1
  intel_extension_for_transformers/llm/library/jblas/jblas/jit_blas_parallel.h
  intel_extension_for_transformers/llm/library/jblas/jblas/kernel_avx2.h
  intel_extension_for_transformers/llm/library/jblas/jblas/kernel_avx512f.h
  intel_extension_for_transformers/llm/library/jblas/jblas/kernel_ref.h
Labels: bug, ready for merge, ITREX-1.3

#1064 Fixed example error for T5 text2text generation
  examples/huggingface/pytorch/text2text-generation/requirements.txt
Labels: bug, ITREX-1.3

#1059 [LLM Runtime] dynamic link the layer to compress binary size
  intel_extension_for_transformers/llm/runtime/graph/CMakeLists.txt
  intel_extension_for_transformers/llm/runtime/graph/cmake/Common.cmake
  intel_extension_for_transformers/llm/runtime/graph/core/CMakeLists.txt
Labels: enhancement, ITREX.cpp, ITREX-1.3

#1055 [LLM] Save && Load INT4 model on CPU
  intel_extension_for_transformers/llm/quantization/nn/modules.py
  intel_extension_for_transformers/llm/quantization/utils.py
  intel_extension_for_transformers/transformers/modeling/modeling_auto.py
  intel_extension_for_transformers/transformers/utils/config.py
  intel_extension_for_transformers/transformers/utils/utility.py
  tests/CI/test_weight_only.py
Labels: ready for merge

#961 [LLM Runtime] Sync inference scripts
  .github/workflows/cpp-graph-test.yml
  .github/workflows/script/models/cpp_graph_inference.sh
  .github/workflows/script/models/local_models.json
  intel_extension_for_transformers/llm/runtime/graph/requirements.txt
  intel_extension_for_transformers/llm/runtime/graph/scripts/ci/calculate_percentiles.py
  intel_extension_for_transformers/llm/runtime/graph/scripts/ci/cpp_graph_inference.sh
  intel_extension_for_transformers/llm/runtime/graph/scripts/ci/cpp_graph_prompts.json
  intel_extension_for_transformers/llm/runtime/graph/scripts/requirements/baichuan.txt
  intel_extension_for_transformers/llm/runtime/graph/scripts/requirements/chatglm-6b.txt
  intel_extension_for_transformers/llm/runtime/graph/scripts/requirements/common.txt
  intel_extension_for_transformers/llm/runtime/graph/scripts/requirements/mistral.txt
Labels: ITREX.cpp, ready for merge

#1065 [NeuralChat] optimize prompt template to decrease model hallucination and enhance the ability of RAG
  intel_extension_for_transformers/neural_chat/pipeline/plugins/prompt/prompt_template.py
  intel_extension_for_transformers/neural_chat/prompts/prompt.py
Labels: NeuralChat

#1053 [LLM Runtime]Magicoder graph
  intel_extension_for_transformers/llm/runtime/graph/README.md
  intel_extension_for_transformers/llm/runtime/graph/core/ne_layers.c
  intel_extension_for_transformers/llm/runtime/graph/core/ne_layers.h
  intel_extension_for_transformers/llm/runtime/graph/models/chatglm/chatglm.cpp
  intel_extension_for_transformers/llm/runtime/graph/models/chatglm/chatglm2.cpp
  intel_extension_for_transformers/llm/runtime/graph/models/falcon/falcon.cpp
  intel_extension_for_transformers/llm/runtime/graph/models/gptj/gptj.cpp
  intel_extension_for_transformers/llm/runtime/graph/models/gptneox/gptneox.cpp
  intel_extension_for_transformers/llm/runtime/graph/models/llama/llama.cpp
  intel_extension_for_transformers/llm/runtime/graph/models/model_utils/model_files.h
  intel_extension_for_transformers/llm/runtime/graph/models/model_utils/model_types.h
  intel_extension_for_transformers/llm/runtime/graph/models/model_utils/model_utils.cpp
  intel_extension_for_transformers/llm/runtime/graph/models/qwen/qwen.cpp
  intel_extension_for_transformers/llm/runtime/graph/scripts/ci/cpp_graph_inference.sh
  intel_extension_for_transformers/llm/runtime/graph/scripts/convert_baichuan.py
  intel_extension_for_transformers/llm/runtime/graph/scripts/convert_bloom.py
  intel_extension_for_transformers/llm/runtime/graph/scripts/convert_chatglm.py
  intel_extension_for_transformers/llm/runtime/graph/scripts/convert_dolly.py
  intel_extension_for_transformers/llm/runtime/graph/scripts/convert_falcon.py
  intel_extension_for_transformers/llm/runtime/graph/scripts/convert_gptj.py
  intel_extension_for_transformers/llm/runtime/graph/scripts/convert_gptneox.py
  intel_extension_for_transformers/llm/runtime/graph/scripts/convert_llama.py
  intel_extension_for_transformers/llm/runtime/graph/scripts/convert_mistral.py
  intel_extension_for_transformers/llm/runtime/graph/scripts/convert_mpt.py
  intel_extension_for_transformers/llm/runtime/graph/scripts/convert_opt.py
  intel_extension_for_transformers/llm/runtime/graph/scripts/convert_qwen.py
  intel_extension_for_transformers/llm/runtime/graph/scripts/convert_starcoder.py
Labels: ITREX.cpp

#1078 [LLM Runtime] Circumvent dependabot check for chatglm/baichuan/baichuan2
  intel_extension_for_transformers/llm/runtime/graph/scripts/ci/cpp_graph_inference.sh
  intel_extension_for_transformers/llm/runtime/graph/scripts/requirements/baichuan.sh
  intel_extension_for_transformers/llm/runtime/graph/scripts/requirements/baichuan.txt
  intel_extension_for_transformers/llm/runtime/graph/scripts/requirements/chatglm-6b.sh
  intel_extension_for_transformers/llm/runtime/graph/scripts/requirements/chatglm-6b.txt
Labels: ITREX.cpp

#1082 [LLM Runtime] support neural chat on windows with magicoder
  intel_extension_for_transformers/llm/runtime/graph/__init__.py
  intel_extension_for_transformers/llm/runtime/graph/scripts/convert_llama.py
  setup.py
Labels: ITREX.cpp, ITREX 1.3.1
