Repository intel/intel-extension-for-transformers, pull requests merged in 2023-11, with the labels that each got.

#567 [LLM Runtime] enable MHA fusion for gptneox&dolly&starcoder&llama2-70b
  intel_extension_for_transformers/llm/runtime/graph/models/gptneox/gptneox.cpp
  intel_extension_for_transformers/llm/runtime/graph/models/gptneox/gptneox_utils.cpp
  intel_extension_for_transformers/llm/runtime/graph/models/llama/llama.cpp
  intel_extension_for_transformers/llm/runtime/graph/models/starcoder/starcoder.cpp
  intel_extension_for_transformers/llm/runtime/graph/models/starcoder/starcoder_utils.cpp
Labels: ITREX.cpp

#596 [Doc] change the structure of llm runtime readme
  intel_extension_for_transformers/llm/runtime/graph/README.md
Labels: documentation, ready for merge

#603 [NeuralChat] Refine askdoc API and retrieval logic
  intel_extension_for_transformers/neural_chat/pipeline/plugins/retrieval/detector/intent_detection.py
  intel_extension_for_transformers/neural_chat/pipeline/plugins/retrieval/indexing/context_utils.py
  intel_extension_for_transformers/neural_chat/pipeline/plugins/retrieval/indexing/indexing.py
  intel_extension_for_transformers/neural_chat/pipeline/plugins/retrieval/retrieval_agent.py
  intel_extension_for_transformers/neural_chat/server/restful/retrieval_api.py
  intel_extension_for_transformers/neural_chat/utils/database/init_db_askdoc.sql
Labels: ITREX-1.3-sprint2, NeuralChat

#620 Fix bloom ffn fusion
  intel_extension_for_transformers/llm/runtime/graph/models/bloom/bloom.cpp
Labels: WIP

#623 [Document] update llm runtime readme
  .github/workflows/script/formatScan/nlp_dict.txt
  README.md
  intel_extension_for_transformers/llm/runtime/graph/README.md
Labels: documentation, ITREX.cpp, ready for merge

#625 [LLM Runtime] Fix LLaMA after discarding KV-cache
  intel_extension_for_transformers/llm/runtime/graph/models/llama/llama.cpp
Labels: ITREX.cpp, ready for merge

#608 [LLM Runtime] Shift-RoPE-based Streaming-LLM for Fused-Attention
  intel_extension_for_transformers/llm/library/jblas/jblas/kernel_jit.h
  intel_extension_for_transformers/llm/runtime/graph/README.md
  intel_extension_for_transformers/llm/runtime/graph/core/README.md
  intel_extension_for_transformers/llm/runtime/graph/core/layers/mha_dense.cpp
  intel_extension_for_transformers/llm/runtime/graph/core/layers/mha_dense.h
  intel_extension_for_transformers/llm/runtime/graph/core/ne_layers.c
  intel_extension_for_transformers/llm/runtime/graph/core/ne_layers.h
  intel_extension_for_transformers/llm/runtime/graph/docs/fused_attention.md
  intel_extension_for_transformers/llm/runtime/graph/docs/imgs/Attention.PNG
  intel_extension_for_transformers/llm/runtime/graph/docs/imgs/FFN.PNG
  intel_extension_for_transformers/llm/runtime/graph/docs/imgs/shift-rope.svg
  intel_extension_for_transformers/llm/runtime/graph/docs/imgs/shuffle-attn.svg
  intel_extension_for_transformers/llm/runtime/graph/docs/infinite_inference.md
  intel_extension_for_transformers/llm/runtime/graph/docs/tensor_parallelism.md
  intel_extension_for_transformers/llm/runtime/graph/models/baichuan/baichuan.cpp
  intel_extension_for_transformers/llm/runtime/graph/models/chatglm/chatglm2.cpp
  intel_extension_for_transformers/llm/runtime/graph/models/falcon/falcon.cpp
  intel_extension_for_transformers/llm/runtime/graph/models/gptj/gptj.cpp
  intel_extension_for_transformers/llm/runtime/graph/models/gptneox/gptneox.cpp
  intel_extension_for_transformers/llm/runtime/graph/models/llama/llama.cpp
  intel_extension_for_transformers/llm/runtime/graph/models/model_utils/model_utils.cpp
  intel_extension_for_transformers/llm/runtime/graph/models/mpt/mpt.cpp
  intel_extension_for_transformers/llm/runtime/graph/models/starcoder/starcoder.cpp
  intel_extension_for_transformers/llm/runtime/graph/scripts/inference.py
  intel_extension_for_transformers/llm/runtime/graph/scripts/run.py
Labels: ITREX.cpp

#565 [LLM Runtime] integrate AVX_VNNI
  intel_extension_for_transformers/llm/runtime/graph/core/README.md
  intel_extension_for_transformers/llm/runtime/graph/core/layers/inner_product.cpp
  intel_extension_for_transformers/llm/runtime/graph/core/layers/ip_fusion_ffn.cpp
  intel_extension_for_transformers/llm/runtime/graph/core/layers/ip_fusion_qkv.cpp
  intel_extension_for_transformers/llm/runtime/graph/core/layers/jblas_common.hpp
Labels: ITREX.cpp, ready for merge

#646 [LLM Runtime] Multi-Round chat with chatglm2
  intel_extension_for_transformers/llm/runtime/graph/README.md
  intel_extension_for_transformers/llm/runtime/graph/application/main_pybind.cpp
  intel_extension_for_transformers/llm/runtime/graph/models/chatglm/chatglm2.cpp
  intel_extension_for_transformers/llm/runtime/graph/models/llama/llama.cpp
  intel_extension_for_transformers/llm/runtime/graph/models/model_utils/model_types.h
Labels: ITREX.cpp, ready for merge

#583 [LLM Runtime] Unify KV_cache and Support Batch-dim Process in Beam Search
  intel_extension_for_transformers/llm/runtime/graph/__init__.py
  intel_extension_for_transformers/llm/runtime/graph/application/main_pybind.cpp
  intel_extension_for_transformers/llm/runtime/graph/application/main_run.cpp
  intel_extension_for_transformers/llm/runtime/graph/application/pybind_gptj.cpp
  intel_extension_for_transformers/llm/runtime/graph/core/ne.h
  intel_extension_for_transformers/llm/runtime/graph/core/ne_layers.c
  intel_extension_for_transformers/llm/runtime/graph/core/ne_layers.h
  intel_extension_for_transformers/llm/runtime/graph/models/baichuan/baichuan.cpp
  intel_extension_for_transformers/llm/runtime/graph/models/bloom/bloom.cpp
  intel_extension_for_transformers/llm/runtime/graph/models/chatglm/chatglm.cpp
  intel_extension_for_transformers/llm/runtime/graph/models/chatglm/chatglm2.cpp
  intel_extension_for_transformers/llm/runtime/graph/models/falcon/falcon.cpp
  intel_extension_for_transformers/llm/runtime/graph/models/gptj/gptj.cpp
  intel_extension_for_transformers/llm/runtime/graph/models/gptneox/gptneox.cpp
  intel_extension_for_transformers/llm/runtime/graph/models/gptneox/gptneox_utils.cpp
  intel_extension_for_transformers/llm/runtime/graph/models/llama/llama.cpp
  intel_extension_for_transformers/llm/runtime/graph/models/model_utils/model_types.h
  intel_extension_for_transformers/llm/runtime/graph/models/model_utils/model_utils.cpp
  intel_extension_for_transformers/llm/runtime/graph/models/model_utils/model_utils.h
  intel_extension_for_transformers/llm/runtime/graph/models/mpt/mpt.cpp
  intel_extension_for_transformers/llm/runtime/graph/models/opt/opt.cpp
  intel_extension_for_transformers/llm/runtime/graph/models/starcoder/starcoder.cpp
  tests/test_llm_runtime.py
Labels: ITREX.cpp, ready for merge

#655 [LLM Runtime] Allow CompileBF16 on GCC11
  .github/workflows/cpp-graph-test.yml
  intel_extension_for_transformers/llm/library/jblas/jblas/jit_blas_utils.h
  intel_extension_for_transformers/llm/library/jblas/jblas/kernel_avx2.h
  intel_extension_for_transformers/llm/library/jblas/jblas/kernel_avx512_bf16.h
  intel_extension_for_transformers/llm/library/jblas/jblas/kernel_avx512f.h
  intel_extension_for_transformers/llm/library/jblas/jblas/kernel_wrapper.h
  intel_extension_for_transformers/llm/runtime/graph/README.md
  intel_extension_for_transformers/llm/runtime/graph/docs/fused_attention.md
Labels: ITREX.cpp, ready for merge

#662 [LLM Runtime] disable bf16 scale for jblas
  .github/workflows/script/models/cpp_graph_inference.sh
  intel_extension_for_transformers/llm/runtime/graph/models/model_utils/model_utils.cpp
Labels: ITREX.cpp, CI

#581 [Example] Add WOQ to code-generation example
  examples/huggingface/pytorch/code-generation/quantization/run_generation.py
Labels: draft

#665 [LLM Runtime] Refine Python API
  intel_extension_for_transformers/llm/runtime/graph/README.md
  intel_extension_for_transformers/llm/runtime/graph/__init__.py
  intel_extension_for_transformers/llm/runtime/graph/application/main_pybind.cpp
  intel_extension_for_transformers/transformers/modeling/modeling_auto.py
  intel_extension_for_transformers/transformers/utils/quantization_config.py
  tests/test_llm_runtime.py
Labels: documentation, ITREX.cpp, ready for merge

#688 [LLM Runtime] Support load_in_nbit in llm runtime
  README.md
  intel_extension_for_transformers/llm/runtime/graph/README.md
  intel_extension_for_transformers/transformers/modeling/modeling_auto.py
Labels: ITREX.cpp

#697 [LLM Runtime] Correct GCC targe options
  intel_extension_for_transformers/llm/library/jblas/jblas/jit_blas_utils.h
  intel_extension_for_transformers/llm/library/jblas/jblas/jit_blas_weight_compression.h
  intel_extension_for_transformers/llm/library/jblas/jblas/jit_blas_wrapper.h
  intel_extension_for_transformers/llm/library/jblas/jblas/kernel_avx512_bf16.h
  intel_extension_for_transformers/llm/library/jblas/jblas/kernel_jit.h
Labels: ITREX.cpp, ready for merge

#696 [LLM Runtime] Update README
  intel_extension_for_transformers/llm/runtime/graph/README.md
  intel_extension_for_transformers/llm/runtime/graph/requirements.txt
  intel_extension_for_transformers/llm/runtime/graph/scripts/convert_baichuan.py
  intel_extension_for_transformers/llm/runtime/graph/scripts/convert_chatglm.py
Labels: ITREX.cpp, ready for merge

#685 [LLM Runtime] Add Script for PPL Evaluation
  .gitignore
  intel_extension_for_transformers/llm/runtime/graph/README.md
  intel_extension_for_transformers/llm/runtime/graph/__init__.py
  intel_extension_for_transformers/llm/runtime/graph/application/main_pybind.cpp
  intel_extension_for_transformers/llm/runtime/graph/requirements.txt
  intel_extension_for_transformers/llm/runtime/graph/scripts/cal_diff.py
  intel_extension_for_transformers/llm/runtime/graph/scripts/perplexity.py
  tests/requirements.txt
  tests/test_llm_runtime.py
Labels: ITREX.cpp, ready for merge

#442 [LLM] Support QLoRA on CPU device
  .github/workflows/script/formatScan/nlp_dict.txt
  docs/qloracpu.md
  intel_extension_for_transformers/llm/finetuning/finetuning.py
  intel_extension_for_transformers/llm/quantization/autograd/__init__.py
  intel_extension_for_transformers/llm/quantization/autograd/functions.py
  intel_extension_for_transformers/llm/quantization/nn/modules.py
  intel_extension_for_transformers/llm/quantization/utils.py
  intel_extension_for_transformers/neural_chat/models/base_model.py
  intel_extension_for_transformers/neural_chat/prompts/prompt.py
  intel_extension_for_transformers/neural_chat/tests/ci/api/test_chatbot_build_api.py
  intel_extension_for_transformers/neural_chat/tests/nightly/finetuning/test_finetuning.py
  tests/test_quantization.py
  tests/test_weight_only.py
Labels: enhancement

#611 [LLM Runtime] Enable GPTQ models
  intel_extension_for_transformers/llm/runtime/graph/README.md
  intel_extension_for_transformers/llm/runtime/graph/__init__.py
  intel_extension_for_transformers/llm/runtime/graph/application/main_pybind.cpp
  intel_extension_for_transformers/llm/runtime/graph/scripts/cal_diff.py
  intel_extension_for_transformers/llm/runtime/graph/scripts/common.py
  intel_extension_for_transformers/llm/runtime/graph/scripts/convert.py
  intel_extension_for_transformers/llm/runtime/graph/scripts/convert_gptq_bloom.py
  intel_extension_for_transformers/llm/runtime/graph/scripts/convert_gptq_llama.py
  intel_extension_for_transformers/llm/runtime/graph/tests/test_llm_runtime.py
  intel_extension_for_transformers/transformers/modeling/modeling_auto.py
  intel_extension_for_transformers/transformers/utils/quantization_config.py
Labels: ITREX.cpp, ready for merge

#639 [LLM Runtime] Add jblas split weight interface and support jblas models
  intel_extension_for_transformers/llm/library/jblas/jblas/jit_blas_weight_compression.h
  intel_extension_for_transformers/llm/runtime/graph/core/layers/jblas_common.cpp
  intel_extension_for_transformers/llm/runtime/graph/core/ne_jblas.h
  intel_extension_for_transformers/llm/runtime/graph/models/gptj/gptj.cpp
  intel_extension_for_transformers/llm/runtime/graph/models/llama/llama.cpp
  intel_extension_for_transformers/llm/runtime/graph/models/model_utils/model_files.h
Labels: ITREX.cpp, CI

#734 [LLM Runtime] Beam Search Support of Fused Attention
  intel_extension_for_transformers/llm/runtime/graph/README.md
  intel_extension_for_transformers/llm/runtime/graph/application/main_pybind.cpp
  intel_extension_for_transformers/llm/runtime/graph/application/pybind_gptj.cpp
  intel_extension_for_transformers/llm/runtime/graph/core/layers/mha_dense.cpp
  intel_extension_for_transformers/llm/runtime/graph/core/layers/mha_dense.h
  intel_extension_for_transformers/llm/runtime/graph/models/model_utils/model_utils.cpp
Labels: ITREX.cpp, ready for merge

#776 [NeuralChat] Support NER with chatbot and upload_link to create new kb
  intel_extension_for_transformers/neural_chat/examples/deployment/photo_ai/backend/photoai.yaml
  intel_extension_for_transformers/neural_chat/models/base_model.py
  intel_extension_for_transformers/neural_chat/pipeline/plugins/ner/ner.py
  intel_extension_for_transformers/neural_chat/pipeline/plugins/retrieval/indexing/indexing.py
  intel_extension_for_transformers/neural_chat/pipeline/plugins/retrieval/retrieval_agent.py
  intel_extension_for_transformers/neural_chat/requirements_hpu.txt
  intel_extension_for_transformers/neural_chat/server/restful/photoai_api.py
  intel_extension_for_transformers/neural_chat/server/restful/photoai_services.py
  intel_extension_for_transformers/neural_chat/server/restful/retrieval_api.py
  intel_extension_for_transformers/neural_chat/server/restful/voicechat_api.py
Labels: NeuralChat, ITREX-1.3

#789 fix : init_from_bin example
  intel_extension_for_transformers/llm/runtime/graph/CMakeLists.txt
  intel_extension_for_transformers/neural_chat/docs/notebooks/build_talkingbot_on_pc.ipynb
  intel_extension_for_transformers/neural_chat/examples/deployment/talkingbot/pc/build_talkingbot_on_pc.ipynb
  setup.py
Labels: ready for merge

#673 [Engine] Apply the STS task to bge models
  examples/huggingface/pytorch/text-classification/deployment/mrpc/bge_large/run_executor.py
  examples/huggingface/pytorch/text-embedding/deployment/mteb/bge/README.md
  examples/huggingface/pytorch/text-embedding/deployment/mteb/bge/engine_model.py
  examples/huggingface/pytorch/text-embedding/deployment/mteb/bge/executor_dataloader.py
  examples/huggingface/pytorch/text-embedding/deployment/mteb/bge/executor_utils.py
  examples/huggingface/pytorch/text-embedding/deployment/mteb/bge/requirements.txt
  examples/huggingface/pytorch/text-embedding/deployment/mteb/bge/run_bge.sh
  examples/huggingface/pytorch/text-embedding/deployment/mteb/bge/run_executor.py
  examples/huggingface/pytorch/text-embedding/deployment/mteb/bge/run_mteb.py
  intel_extension_for_transformers/llm/runtime/deprecated/compile/graph/graph.py
  intel_extension_for_transformers/llm/runtime/deprecated/compile/sub_graph/multi_head_attention.py
  intel_extension_for_transformers/llm/runtime/deprecated/compile/sub_graph/subgraph_matcher.py
  intel_extension_for_transformers/transformers/modeling/modeling_auto.py
Labels: ITREX.cpp, ITREX-1.3

#805 [NeuralChat] Fix the print bug in retriever
  intel_extension_for_transformers/neural_chat/pipeline/plugins/retrieval/retrieval_agent.py
Labels: bug, ITREX-1.3

#804 fix tts and face animation UT on gpu
  intel_extension_for_transformers/neural_chat/pipeline/plugins/video/face_animation/src/facerender/modules/make_animation.py
  intel_extension_for_transformers/neural_chat/tests/ci/api/test_chatbot_build_api.py
Labels: bug, NeuralChat, ITREX-1.3

#812 [LLM Runtime]fix format
  intel_extension_for_transformers/llm/runtime/graph/core/ne_layers.h
  intel_extension_for_transformers/llm/runtime/graph/models/whisper/dr_wav.h
  intel_extension_for_transformers/llm/runtime/graph/models/whisper/whisper.cpp
  intel_extension_for_transformers/llm/runtime/graph/models/whisper/whisper.h
  intel_extension_for_transformers/llm/runtime/graph/models/whisper/whisper_utils.cpp
Labels: bug, ITREX-1.3

#793 [LLM Runtime] fix added_tokens error
  intel_extension_for_transformers/llm/runtime/graph/__init__.py
  intel_extension_for_transformers/llm/runtime/graph/scripts/convert_llama.py
  intel_extension_for_transformers/llm/runtime/graph/scripts/convert_mistral.py
Labels: bug, ITREX.cpp, ITREX-1.3

#802 [NeuralChat] Support Gaudi model parallelism serving
  intel_extension_for_transformers/neural_chat/config.py
  intel_extension_for_transformers/neural_chat/examples/deployment/textbot/backend/gaudi/README.md
  intel_extension_for_transformers/neural_chat/examples/deployment/textbot/backend/gaudi/run_text_chat.py
  intel_extension_for_transformers/neural_chat/examples/deployment/textbot/backend/gaudi/textbot.yaml
  intel_extension_for_transformers/neural_chat/examples/deployment/textbot/backend/xeon/README.md
  intel_extension_for_transformers/neural_chat/examples/deployment/textbot/backend/xeon/run.sh
  intel_extension_for_transformers/neural_chat/examples/deployment/textbot/backend/xeon/run_text_chat.py
  intel_extension_for_transformers/neural_chat/examples/deployment/textbot/backend/xeon/textbot.yaml
  intel_extension_for_transformers/neural_chat/server/multi_hpu_server.py
  intel_extension_for_transformers/neural_chat/server/neuralchat_server.py
  intel_extension_for_transformers/neural_chat/server/restful/api.py
  intel_extension_for_transformers/neural_chat/server/restful/faceanimation_api.py
  intel_extension_for_transformers/neural_chat/server/restful/finetune_api.py
  intel_extension_for_transformers/neural_chat/server/restful/photoai_api.py
  intel_extension_for_transformers/neural_chat/server/restful/retrieval_api.py
  intel_extension_for_transformers/neural_chat/server/restful/text2image_api.py
  intel_extension_for_transformers/neural_chat/server/restful/textchat_api.py
  intel_extension_for_transformers/neural_chat/server/restful/voicechat_api.py
Labels: NeuralChat, ITREX-1.3

#99 [LLM] Add UT for INCModelForSeq2SeqLM
  intel_extension_for_transformers/transformers/modeling/modeling_base_seq2seq.py
  setup.py
  tests/CI/test_modeling.py
Labels: ready for merge, ITREX-1.3

#462 [NeuralChat] Enable finetune for Qwen-7b-chat on CPU (WIP)
  intel_extension_for_transformers/llm/finetuning/finetuning.py
Labels: NeuralChat

#819 [NeuralChat] update llava model import path
  intel_extension_for_transformers/neural_chat/examples/finetuning/multi_modal/train.py
  intel_extension_for_transformers/transformers/modeling/__init__.py
  intel_extension_for_transformers/transformers/modeling/llava_models/__init__.py
  tests/CI/test_llava.py
Labels: enhancement, ITREX-1.3

#814 [LLM] Support chatglm/falcon series and unified int8 loading
  examples/huggingface/pytorch/code-generation/quantization/run_generation.py
  examples/huggingface/pytorch/text-generation/quantization/run_benchmark.sh
  examples/huggingface/pytorch/text-generation/quantization/run_generation.py
  examples/huggingface/pytorch/text-generation/quantization/run_tuning.sh
  intel_extension_for_transformers/llm/evaluation/models.py
  intel_extension_for_transformers/neural_chat/models/model_utils.py
  intel_extension_for_transformers/transformers/modeling/modeling_auto.py
  intel_extension_for_transformers/transformers/utils/quantization_config.py
  intel_extension_for_transformers/transformers/utils/utility.py
  tests/Nightly/test_llm_smoothquant.py
  tests/requirements.txt
Labels: enhancement, ITREX-1.3

#820 fix finetuning instruction readme issue
  intel_extension_for_transformers/neural_chat/examples/finetuning/instruction/README.md
Labels: documentation, ITREX-1.3

#822 [NeuralChat] Fix ner nightly ut bug
  intel_extension_for_transformers/neural_chat/chatbot.py
  intel_extension_for_transformers/neural_chat/pipeline/plugins/ner/ner.py
  intel_extension_for_transformers/neural_chat/pipeline/plugins/ner/ner_int.py
  intel_extension_for_transformers/neural_chat/plugins.py
  intel_extension_for_transformers/neural_chat/tests/nightly/plugins/test_ner.py
Labels: bug, NeuralChat, ITREX-1.3

#771 Update ppo readme
  intel_extension_for_transformers/neural_chat/examples/finetuning/ppo_pipeline/README.md
  intel_extension_for_transformers/neural_chat/examples/finetuning/ppo_pipeline/merge_peft_adapter.py
  intel_extension_for_transformers/neural_chat/examples/finetuning/ppo_pipeline/reward_modeling.py
  intel_extension_for_transformers/neural_chat/examples/finetuning/ppo_pipeline/rl_training.py
  intel_extension_for_transformers/transformers/modeling/trl_models/modeling_base.py
  intel_extension_for_transformers/transformers/ppo_trainer.py
Labels: documentation, ITREX-1.3
