Repository intel/intel-extension-for-transformers, pull requests merged in 2024-04, with the labels that each got.

#1428 Support AutoRound quantization method for intel GPU
  docs/weightonlyquant.md
  examples/.config/pytorch_optimize.json
  examples/huggingface/pytorch/text-generation/quantization/README.md
  examples/huggingface/pytorch/text-generation/quantization/requirements.txt
  examples/huggingface/pytorch/text-generation/quantization/requirements_GPU.txt
  examples/huggingface/pytorch/text-generation/quantization/run_benchmark.sh
  examples/huggingface/pytorch/text-generation/quantization/run_generation.py
  examples/huggingface/pytorch/text-generation/quantization/run_generation_gpu_woq.py
  examples/huggingface/pytorch/text-generation/quantization/run_tuning.sh
  intel_extension_for_transformers/transformers/llm/evaluation/lm_eval/evaluator.py
  intel_extension_for_transformers/transformers/llm/quantization/nn/modules.py
  intel_extension_for_transformers/transformers/llm/quantization/utils.py
  intel_extension_for_transformers/transformers/modeling/modeling_auto.py
  intel_extension_for_transformers/transformers/utils/config.py
Labels: WIP, ITREX1.4

#1449 [Transformers] Support load mode from HF Hub when use Neural Speed
  examples/.config/pytorch_optimize.json
  examples/huggingface/neural_speed/perplexity/requirements.txt
  examples/huggingface/neural_speed/requirements.txt
  examples/huggingface/neural_speed/run_accuracy.py
  examples/huggingface/pytorch/text-generation/quantization/requirements.txt
  examples/huggingface/pytorch/text-generation/quantization/run_benchmark.sh
  examples/huggingface/pytorch/text-generation/quantization/run_generation.py
  examples/huggingface/pytorch/text-generation/quantization/run_generation_gpu_woq.py
  examples/huggingface/pytorch/text-generation/quantization/run_tuning.sh
  intel_extension_for_transformers/transformers/llm/evaluation/lm_eval/evaluator.py
  intel_extension_for_transformers/transformers/llm/evaluation/lm_eval/models/huggingface.py
  intel_extension_for_transformers/transformers/modeling/modeling_auto.py
Labels: ITREX1.4

#1466 [Transformers] Refine Model `from_pretrained` When `use_neural_speed`
  README.md
  examples/huggingface/pytorch/text-generation/quantization/run_generation.py
  intel_extension_for_transformers/transformers/llm/evaluation/lm_eval/models/huggingface.py
  intel_extension_for_transformers/transformers/modeling/modeling_auto.py
  tests/Nightly/test_llm_runtime.py
  tests/Nightly/test_neural_speed.py
Labels: enhancement, extension, ready for merge

#1460 support ipex arc test
  examples/.config/pytorch_optimize.json
Labels: CI

#1471 Adapted textual inversion distillation for quantization example to latest transformers and diffusers packages
  examples/huggingface/pytorch/textual-inversion/distillation_for_quantization/requirements.txt
  examples/huggingface/pytorch/textual-inversion/distillation_for_quantization/text2images.py
  examples/huggingface/pytorch/textual-inversion/distillation_for_quantization/textual_inversion.py
Labels: bug

#1473 fix QBits actshuf buf overflow under large batch
  .github/workflows/script/formatScan/pylint.sh
  examples/huggingface/pytorch/text-generation/quantization/run_generation.py
  intel_extension_for_transformers/qbits/CMakeLists.txt
  intel_extension_for_transformers/qbits/__init__.py
  intel_extension_for_transformers/qbits/dispatcher/CMakeLists.txt
  intel_extension_for_transformers/qbits/dispatcher/include/bestla_customop.hpp
  intel_extension_for_transformers/qbits/dispatcher/include/bestla_gemm_dispatcher.hpp
  intel_extension_for_transformers/qbits/dispatcher/include/bestla_packq_impl.hpp
  intel_extension_for_transformers/qbits/dispatcher/include/bestla_weightonly_dispatcher.hpp
  intel_extension_for_transformers/qbits/dispatcher/include/dispatcher_utils.hpp
  intel_extension_for_transformers/qbits/dispatcher/neural_speed.cmake
  intel_extension_for_transformers/qbits/dispatcher/src/bestla_gemm_dispatcher.cpp
  intel_extension_for_transformers/qbits/dispatcher/src/bestla_packq_impl.cpp
  intel_extension_for_transformers/qbits/dispatcher/src/bestla_weightonly_dispatcher.cpp
  intel_extension_for_transformers/qbits/dispatcher/src/dispatcher_utils.cpp
  intel_extension_for_transformers/qbits/include/dropout.hpp
  intel_extension_for_transformers/qbits/qbits.cpp
  intel_extension_for_transformers/qbits/qbits_ut/test_dropout.py
  intel_extension_for_transformers/qbits/qbits_ut/test_matmul.py
  intel_extension_for_transformers/qbits/qbits_ut/test_packq.py
  intel_extension_for_transformers/qbits/qbits_ut/test_weightonly.py
  intel_extension_for_transformers/qbits/qbits_ut/ut_utils.py
  intel_extension_for_transformers/qbits/run_build.sh
  intel_extension_for_transformers/qbits/src/dropout.cpp
  intel_extension_for_transformers/transformers/llm/operator/.clang-format
  intel_extension_for_transformers/transformers/llm/operator/CMakeLists.txt
  intel_extension_for_transformers/transformers/utils/config.py
  setup.py
Labels: ready for merge

#1489 Support multiple weight dtype
  examples/.config/pytorch_optimize.json
  examples/huggingface/pytorch/text-generation/quantization/run_tuning.sh
Labels: v1.4.1

#1491 doc: add example for autoround and llama3 on intel gpu
  README.md
  docs/weightonlyquant.md
  examples/huggingface/pytorch/text-generation/quantization/README.md
Labels: v1.4.1

#1495 [Doc] update news
  README.md
Labels: v1.4.1

#1488 Fixed loading issue of woq model with parameters
  intel_extension_for_transformers/transformers/modeling/modeling_auto.py
Labels: v1.4.1

#1496 update neuralchat notebook on cpu
  intel_extension_for_transformers/neural_chat/docs/notebooks/amp_optimization_on_spr.ipynb
  intel_extension_for_transformers/neural_chat/docs/notebooks/build_chatbot_on_icx.ipynb
  intel_extension_for_transformers/neural_chat/docs/notebooks/build_chatbot_on_spr.ipynb
  intel_extension_for_transformers/neural_chat/docs/notebooks/customize_chatbot_with_finetuned_models.ipynb
  intel_extension_for_transformers/neural_chat/docs/notebooks/customize_chatbot_with_plugins.ipynb
  intel_extension_for_transformers/neural_chat/docs/notebooks/deploy_chatbot_on_icx.ipynb
  intel_extension_for_transformers/neural_chat/docs/notebooks/finetune_neuralchat_v2_on_Nvidia_GPU.ipynb
  intel_extension_for_transformers/neural_chat/docs/notebooks/finetuning_on_nv_a100.ipynb
  intel_extension_for_transformers/neural_chat/docs/notebooks/itrex_llm_graph_int4_optimization_on_spr.ipynb
  intel_extension_for_transformers/neural_chat/docs/notebooks/setup_talking_chatbot_service_on_spr.ipynb
  intel_extension_for_transformers/neural_chat/docs/notebooks/setup_text_chatbot_with_caching_on_spr.ipynb
  intel_extension_for_transformers/neural_chat/docs/notebooks/single_node_finetuning_on_spr.ipynb
  intel_extension_for_transformers/neural_chat/docs/notebooks/transformers_extension_api.ipynb
  intel_extension_for_transformers/neural_chat/pipeline/plugins/audio/requirements.txt
Labels: v1.4.1

#1492 Fix example llm recipes and autoround default value.
  examples/huggingface/pytorch/text-generation/quantization/README.md
  examples/huggingface/pytorch/text-generation/quantization/llm_quantization_recipes.md
  examples/huggingface/pytorch/text-generation/quantization/requirements_cpu_woq.txt
  examples/huggingface/pytorch/text-generation/quantization/run_benchmark.sh
  examples/huggingface/pytorch/text-generation/quantization/run_generation_cpu_woq.py
  examples/huggingface/pytorch/text-generation/quantization/run_generation_gpu_woq.py
  examples/huggingface/pytorch/text-generation/quantization/run_generation_sq.py
  examples/huggingface/pytorch/text-generation/quantization/run_tuning.sh
  intel_extension_for_transformers/transformers/llm/evaluation/lm_eval/evaluator.py
  tests/requirements.txt
Labels: v1.4.1

#1499 improve low bits model loading
  intel_extension_for_transformers/transformers/modeling/modeling_auto.py
Labels: v1.4.1
