Repository intel/intel-extension-for-transformers, pull requests merged in 2024-03, with the labels that each got.

#1380 Support IPEX bf16 & fp32 optimization for emebedding model
  intel_extension_for_transformers/neural_chat/pipeline/plugins/retrieval/retrieval_agent.py
  intel_extension_for_transformers/neural_chat/tests/ci/plugins/retrieval/test_parameters.py
Labels: NeuralChat

#1387 [NeuralChat] Fix index error in Child-parent retriever
  intel_extension_for_transformers/langchain/retrievers/child_parent_retriever.py
Labels: bug, ITREX1.4

#1388 [NeuralChat] Fix tgi endpoint in test
  intel_extension_for_transformers/neural_chat/tests/nightly/serving/test_tgi_serving.py
Labels: bug, ITREX1.4

#1389 Clean dependencies in requirements.txt and setup.py
  examples/huggingface/pytorch/text-generation/README.md
  examples/huggingface/pytorch/text-generation/quantization/README.md
  intel_extension_for_transformers/llm/quantization/utils.py
  requirements-cpu.txt
  requirements-gpu.txt
  requirements.txt
  setup.py
  setup_env_gpu.sh
Labels: enhancement, ITREX1.4

#1384 modify readme
  docker/README.md
  docker/docker-compose.yml
  intel_extension_for_transformers/neural_chat/docker/code_generation/README.md
  intel_extension_for_transformers/neural_chat/docker/code_generation/cpu/Dockerfile
  intel_extension_for_transformers/neural_chat/docker/finetuning/Dockerfile
  intel_extension_for_transformers/neural_chat/docker/finetuning/README.md
  intel_extension_for_transformers/neural_chat/docker/text_generation/README.md
  intel_extension_for_transformers/neural_chat/docker/text_generation/cpu/Dockerfile
Labels: ITREX1.4

#1390 Update README for intel GPU weight only quantization
  examples/huggingface/pytorch/text-generation/quantization/README.md
  requirements-cpu.txt
Labels: documentation, ITREX1.4

#1396 update test
  .github/checkgroup.yml
  .github/workflows/deploy-test.yml
  .github/workflows/format_scan.yml
  .github/workflows/optimize-test.yml
  .github/workflows/script/formatScan/pylint.sh
  .github/workflows/script/install_binary.sh
  .github/workflows/script/prepare_env_with_conda.sh
  .github/workflows/script/unitTest/run_unit_test_neuralchat.sh
  .github/workflows/sparse_lib_CI.yml
  .github/workflows/unit-test-engine.yml
  .github/workflows/unit-test-kernel.yml
  .github/workflows/unit-test-neuralchat.yml
  .github/workflows/unit-test-neuralspeed.yml
  .github/workflows/unit-test-optimize.yml
  docs/publication.md
Labels: CI

#1399 Promote qbits as itrex module
  docs/qbits.md
  intel_extension_for_transformers/transformers/llm/operator/csrc/CMakeLists.txt
  intel_extension_for_transformers/transformers/llm/operator/csrc/dispatcher/CMakeLists.txt
  intel_extension_for_transformers/transformers/llm/operator/csrc/dispatcher/include/bestla_packq_impl.hpp
  intel_extension_for_transformers/transformers/llm/operator/csrc/dispatcher/include/bestla_weightonly_dispatcher.hpp
  intel_extension_for_transformers/transformers/llm/operator/csrc/dispatcher/src/bestla_packq_impl.cpp
  intel_extension_for_transformers/transformers/llm/operator/csrc/dispatcher/src/bestla_weightonly_dispatcher.cpp
  intel_extension_for_transformers/transformers/llm/operator/csrc/qbits.cpp
  intel_extension_for_transformers/transformers/llm/operator/csrc/qbits_ut/test_dropout.py
  intel_extension_for_transformers/transformers/llm/operator/csrc/qbits_ut/test_matmul.py
  intel_extension_for_transformers/transformers/llm/operator/csrc/qbits_ut/test_packq.py
  intel_extension_for_transformers/transformers/llm/operator/csrc/qbits_ut/test_weightonly.py
  intel_extension_for_transformers/transformers/llm/operator/csrc/qbits_ut/ut_utils.py
  intel_extension_for_transformers/transformers/llm/quantization/autograd/functions.py
  intel_extension_for_transformers/transformers/llm/quantization/nn/modules.py
  setup.py
  tests/CI/test_weight_only.py
Labels: ready for merge

#1410 Remove redundant parameters for WOQ saving config and fix GPTQ issue
  examples/huggingface/pytorch/code-generation/quantization/README.md
  examples/huggingface/pytorch/text-generation/quantization/README.md
  examples/huggingface/pytorch/text-generation/quantization/run_generation.py
  intel_extension_for_transformers/transformers/llm/quantization/nn/modules.py
  intel_extension_for_transformers/transformers/llm/quantization/utils.py
  intel_extension_for_transformers/transformers/modeling/modeling_auto.py
  intel_extension_for_transformers/transformers/utils/config.py
Labels: ready for merge

#1424 [NeuralChat] Fix code generation code format issue
  intel_extension_for_transformers/neural_chat/server/restful/codegen_api.py
Labels: bug, ITREX1.4

#1358 [NeuralChat] Adding LLaVA-NeXT
  intel_extension_for_transformers/neural_chat/examples/finetuning/multi_modal/eval/mmmu_eval/run_llava.py
  intel_extension_for_transformers/neural_chat/examples/finetuning/multi_modal/llava_utils.py
  intel_extension_for_transformers/neural_chat/examples/finetuning/multi_modal/scripts/llava_next/pretrain_mistral.sh
  intel_extension_for_transformers/neural_chat/examples/finetuning/multi_modal/train.py
  intel_extension_for_transformers/transformers/modeling/llava_models/llava_arch.py
  intel_extension_for_transformers/transformers/modeling/llava_models/llava_mistral.py
  intel_extension_for_transformers/transformers/modeling/llava_models/mm_utils.py
  intel_extension_for_transformers/transformers/modeling/llava_models/multimodal_encoder/clip_encoder.py
  tests/CI/test_llava.py
Labels: ITREX1.4

#1382 [Neural Speed]load model from modelscope
  README.md
  examples/huggingface/neural_speed/perplexity/requirements.txt
  examples/huggingface/neural_speed/requirements.txt
  intel_extension_for_transformers/llm/runtime/neural_speed/requirements.txt
  intel_extension_for_transformers/neural_chat/requirements.txt
  intel_extension_for_transformers/neural_chat/requirements_cpu.txt
  intel_extension_for_transformers/neural_chat/tests/requirements.txt
  intel_extension_for_transformers/transformers/modeling/modeling_auto.py
  tests/requirements.txt
Labels: ITREX1.4

#1426 [Example] Update Neural_Speed Eval
  examples/huggingface/neural_speed/run_accuracy.py
  intel_extension_for_transformers/transformers/llm/evaluation/lm_eval/models/huggingface.py
Labels: bug, ITREX1.4

#1422 fix a bug in run_generation_gpu_woq.py
  examples/huggingface/pytorch/text-generation/quantization/run_generation_gpu_woq.py
Labels: bug, ITREX1.4

#1437 Unify the parameters for woq examples by CPU and GPU
  examples/huggingface/pytorch/text-generation/quantization/README.md
  examples/huggingface/pytorch/text-generation/quantization/run_generation_gpu_woq.py
Labels: ready for merge
