Repository intel/intel-extension-for-transformers, pull requests merged in 2024-01, with the labels that each got.

#1100 [LLM Runtime] Fix convert mistral script missing parameter issue
  intel_extension_for_transformers/llm/runtime/graph/scripts/convert_mistral.py
Labels: bug, Migrate to NeuralSpeed

#1076 Enable Qdrant vectorstore
  intel_extension_for_transformers/langchain/vectorstores/__init__.py
  intel_extension_for_transformers/langchain/vectorstores/qdrant.py
  intel_extension_for_transformers/neural_chat/pipeline/plugins/retrieval/retrieval_agent.py
  intel_extension_for_transformers/neural_chat/requirements.txt
  intel_extension_for_transformers/neural_chat/requirements_cpu.txt
  intel_extension_for_transformers/neural_chat/requirements_hpu.txt
  intel_extension_for_transformers/neural_chat/requirements_pc.txt
  intel_extension_for_transformers/neural_chat/requirements_xpu.txt
  intel_extension_for_transformers/neural_chat/tests/ci/api/test_chatbot_build_api.py
  intel_extension_for_transformers/neural_chat/tests/ci/api/test_inference.py
  intel_extension_for_transformers/neural_chat/tests/requirements.txt
Labels: NeuralChat, ITREX 1.3.1

#1080 [NeuralChat] Optimize the prompt follow the suggestion from cnvrg.io team
  intel_extension_for_transformers/neural_chat/pipeline/plugins/prompt/prompt_template.py
Labels: NeuralChat, ITREX 1.3.1

#1119 [NeuralChat] Update the readme for RAG
  intel_extension_for_transformers/neural_chat/pipeline/plugins/retrieval/README.md
Labels: NeuralChat, ITREX 1.3.1

#1121 Fix unexpected keyword argument 'trust_remote_code' in embedding
  intel_extension_for_transformers/langchain/embeddings/optimized_instructor_embedding.py
  intel_extension_for_transformers/langchain/embeddings/optimized_sentence_transformers.py
Labels: bug

#1123 [Runtime] calculate accuracy of runtime
  .github/workflows/cpp-graph-test.yml
  examples/huggingface/llmruntime/runtime_acc.py
  intel_extension_for_transformers/llm/evaluation/lm_eval/models/huggingface.py
  intel_extension_for_transformers/llm/runtime/graph/__init__.py
  intel_extension_for_transformers/llm/runtime/graph/application/main_pybind.cpp
  intel_extension_for_transformers/llm/runtime/graph/scripts/ci/cpp_graph_inference.sh
  intel_extension_for_transformers/llm/runtime/graph/scripts/common.py
  intel_extension_for_transformers/llm/runtime/graph/scripts/convert_gptq_llama.py
  intel_extension_for_transformers/llm/runtime/graph/scripts/convert_gptq_mistral.py
  intel_extension_for_transformers/llm/runtime/graph/scripts/convert_llama.py
  intel_extension_for_transformers/llm/runtime/graph/scripts/convert_mistral.py
Labels: ITREX.cpp, Migrate to NeuralSpeed

#948 [NeuralChat] support llama series model for llava finetuning.
  intel_extension_for_transformers/neural_chat/examples/finetuning/multi_modal/README.md
  intel_extension_for_transformers/neural_chat/examples/finetuning/multi_modal/train.py
  intel_extension_for_transformers/transformers/modeling/llava_models/__init__.py
  intel_extension_for_transformers/transformers/modeling/llava_models/llava_llama.py
Labels: enhancement, ITREX 1.3.1

#1112 [NeuralChat] Support compatible stats format
  intel_extension_for_transformers/neural_chat/config.py
  intel_extension_for_transformers/neural_chat/models/base_model.py
  intel_extension_for_transformers/neural_chat/models/model_utils.py
  intel_extension_for_transformers/neural_chat/tests/ci/api/test_chatbot_build_api.py
  workflows/chatbot/inference/generate.py
Labels: ITREX 1.3.1

#1132 [Neuralchat] Improve error code UT coverage
  intel_extension_for_transformers/neural_chat/chatbot.py
  intel_extension_for_transformers/neural_chat/models/base_model.py
  intel_extension_for_transformers/neural_chat/models/model_utils.py
  intel_extension_for_transformers/neural_chat/pipeline/plugins/retrieval/parser/parser.py
  intel_extension_for_transformers/neural_chat/pipeline/plugins/retrieval/retrieval_agent.py
  intel_extension_for_transformers/neural_chat/pipeline/plugins/security/safety_checker.py
  intel_extension_for_transformers/neural_chat/tests/ci/api/test_chatbot_exception.py
  intel_extension_for_transformers/neural_chat/tests/ci/api/test_chatbot_normal.py
  intel_extension_for_transformers/neural_chat/tests/ci/models/test_model_utils.py
  intel_extension_for_transformers/neural_chat/utils/error_utils.py
Labels: NeuralChat, ITREX 1.3.1

#1151 [LLM Runtime] Add python API for GGUF
  intel_extension_for_transformers/llm/runtime/graph/README.md
  intel_extension_for_transformers/transformers/modeling/modeling_auto.py
Labels: ITREX 1.3.1

#1107 Add WOQ GPTQ frontend and example
  examples/.config/pytorch_optimize.json
  examples/huggingface/pytorch/text-generation/quantization/run_benchmark.sh
  examples/huggingface/pytorch/text-generation/quantization/run_generation.py
  examples/huggingface/pytorch/text-generation/quantization/run_tuning.sh
  intel_extension_for_transformers/llm/operator/csrc/qbits_ut/test_packq.py
  intel_extension_for_transformers/llm/quantization/autograd/functions.py
  intel_extension_for_transformers/llm/quantization/gptq_utils.py
  intel_extension_for_transformers/llm/quantization/nn/modules.py
  intel_extension_for_transformers/llm/quantization/utils.py
  intel_extension_for_transformers/transformers/utils/config.py
  tests/CI/test_quantization.py
Labels: WIP, ITREX 1.3.1

#1143 remove transformers==4.34.1
  .github/workflows/script/unitTest/run_unit_test_optimize.sh
  docker/Dockerfile_chatbot
  intel_extension_for_transformers/neural_chat/docker/Dockerfile
Labels: ITREX 1.3.1

#1159 [Runtime] Add NS PPL example
  .gitignore
  examples/huggingface/neural_speed/perplexity/.gitignore
  examples/huggingface/neural_speed/perplexity/README.md
  examples/huggingface/neural_speed/perplexity/perplexity.py
  examples/huggingface/neural_speed/perplexity/requirements.txt
  examples/huggingface/neural_speed/runtime_acc.py
Labels: ITREX.cpp, ITREX 1.3.1

#1162 [NeuralChat] fix finetuning example import issue.
  intel_extension_for_transformers/neural_chat/examples/finetuning/instruction/finetune_clm.py
Labels: NeuralChat, ITREX 1.3.1

#1163 remove GPTQ llama dependence
  examples/huggingface/pytorch/text-generation/quantization/run_generation.py
  intel_extension_for_transformers/llm/quantization/gptq_utils.py
  intel_extension_for_transformers/llm/quantization/nn/modules.py
  intel_extension_for_transformers/llm/quantization/utils.py
Labels: enhancement, ITREX 1.3.1

#1146 [NeuralChat] Continue refine documents
  intel_extension_for_transformers/neural_chat/README.md
  intel_extension_for_transformers/neural_chat/docs/neuralchat_api.md
  intel_extension_for_transformers/neural_chat/server/config/neuralchat.yaml
  intel_extension_for_transformers/neural_chat/server/restful/api.py
  intel_extension_for_transformers/neural_chat/server/restful/plugin_image2image_api.py
Labels: ITREX 1.3.1

#1120 [NeuralChat] Support vLLM serving
  intel_extension_for_transformers/neural_chat/chatbot.py
  intel_extension_for_transformers/neural_chat/config.py
  intel_extension_for_transformers/neural_chat/examples/serving/triton_inference_sever/README.md
  intel_extension_for_transformers/neural_chat/examples/serving/vllm/README.md
  intel_extension_for_transformers/neural_chat/examples/serving/vllm/textbot_vllm.yaml
  intel_extension_for_transformers/neural_chat/models/base_model.py
  intel_extension_for_transformers/neural_chat/models/model_utils.py
  intel_extension_for_transformers/neural_chat/requirements.txt
  intel_extension_for_transformers/neural_chat/server/neuralchat_server.py
  intel_extension_for_transformers/neural_chat/server/restful/openai_protocol.py
  intel_extension_for_transformers/neural_chat/server/restful/textchat_api.py
  intel_extension_for_transformers/neural_chat/tests/nightly/serving/test_textchat_server_vllm.py
  intel_extension_for_transformers/neural_chat/tests/nightly/serving/test_textchat_server_vllm_async.py
  intel_extension_for_transformers/neural_chat/tests/requirements.txt
Labels: ITREX1.3.2

#1149 [LLM Runtime]update README and requirements
  README.md
  intel_extension_for_transformers/llm/runtime/graph/README.md
  intel_extension_for_transformers/llm/runtime/graph/requirements.txt
  requirements.txt
Labels: ready for merge, ITREX 1.3.1

#1160 [LLM Runtime]Add GGUF API UT
  intel_extension_for_transformers/llm/runtime/graph/tests/test_llm_runtime.py
Labels: ITREX 1.3.1

#1153 Support weight-only kernel with IPEX for intel GPU
  .github/workflows/script/formatScan/nlp_dict.txt
  .gitignore
  docs/weightonlyquant.md
  env_gpu.sh
  examples/huggingface/pytorch/text-generation/quantization/run_generation.py
  examples/huggingface/pytorch/text-generation/quantization/run_generation_gpu_woq.py
  intel_extension_for_transformers/llm/quantization/nn/__init__.py
  intel_extension_for_transformers/llm/quantization/utils.py
  intel_extension_for_transformers/transformers/modeling/modeling_auto.py
  intel_extension_for_transformers/transformers/utils/config.py
  intel_extension_for_transformers/transformers/utils/utility.py
  intel_extension_for_transformers/utils/data_augmentation.py
  intel_extension_for_transformers/utils/utils.py
  requirements-gpu.txt
  setup.py
  setup_env_gpu.sh
  tests/CI/test_data_augmentation.py
  tests/CI/test_quantization.py
  tests/CI/test_weight_only_gpu.py
  tests/README.md
Labels: ITREX 1.3.1
