Repository intel/intel-extension-for-transformers, pull requests merged in 2024-02, with the labels that each got.

#1227 Set trainer.save_model state_dict format to safetensors
  intel_extension_for_transformers/transformers/modeling/model.py
  intel_extension_for_transformers/transformers/trainer.py
Labels: extension

#1231 [NeuralChat] Add ROME implementation and example
  intel_extension_for_transformers/neural_chat/tests/ci/tools/test_rome.py
  intel_extension_for_transformers/neural_chat/tests/nightly/tools/test_rome.py
  intel_extension_for_transformers/neural_chat/tools/rome/__init__.py
  intel_extension_for_transformers/neural_chat/tools/rome/compute_u.py
  intel_extension_for_transformers/neural_chat/tools/rome/compute_v.py
  intel_extension_for_transformers/neural_chat/tools/rome/examples/README.md
  intel_extension_for_transformers/neural_chat/tools/rome/examples/editor.py
  intel_extension_for_transformers/neural_chat/tools/rome/examples/example.json
  intel_extension_for_transformers/neural_chat/tools/rome/examples/requirements.txt
  intel_extension_for_transformers/neural_chat/tools/rome/layer_stats.py
  intel_extension_for_transformers/neural_chat/tools/rome/repr_tools.py
  intel_extension_for_transformers/neural_chat/tools/rome/rome_hparams.py
  intel_extension_for_transformers/neural_chat/tools/rome/rome_impl.py
  intel_extension_for_transformers/neural_chat/tools/rome/tok_dataset.py
  intel_extension_for_transformers/neural_chat/tools/rome/utils/__init__.py
  intel_extension_for_transformers/neural_chat/tools/rome/utils/context.py
  intel_extension_for_transformers/neural_chat/tools/rome/utils/nethook.py
  intel_extension_for_transformers/neural_chat/tools/rome/utils/runningstats.py
Labels: NeuralChat

#1264 [NeuralChat] Retrieval pdf figure to text
  intel_extension_for_transformers/neural_chat/chatbot.py
  intel_extension_for_transformers/neural_chat/pipeline/plugins/retrieval/parser/context_utils.py
  intel_extension_for_transformers/neural_chat/pipeline/plugins/retrieval/parser/html_parser.py
  intel_extension_for_transformers/neural_chat/pipeline/plugins/retrieval/requirements.txt
  intel_extension_for_transformers/neural_chat/tests/requirements.txt
Labels: NeuralChat

#1289 [NeuralChat] Fix local model check issue
  intel_extension_for_transformers/neural_chat/server/restful/textchat_api.py
Labels: ITREX1.3.2

#1189 [NeuralChat] Enhance Retrieval UTs
  intel_extension_for_transformers/neural_chat/assets/docs/retrieve_multi_doc/sample.txt
  intel_extension_for_transformers/neural_chat/assets/docs/retrieve_multi_doc/sample_1.txt
  intel_extension_for_transformers/neural_chat/assets/docs/sample.csv
  intel_extension_for_transformers/neural_chat/assets/docs/sample.html
  intel_extension_for_transformers/neural_chat/assets/docs/sample.md
  intel_extension_for_transformers/neural_chat/assets/docs/sample.pdf
  intel_extension_for_transformers/neural_chat/assets/docs/sample_1.txt
  intel_extension_for_transformers/neural_chat/tests/ci/api/test_chatbot_build_api.py
  intel_extension_for_transformers/neural_chat/tests/ci/api/test_chatbot_normal.py
  intel_extension_for_transformers/neural_chat/tests/ci/api/test_inference.py
  intel_extension_for_transformers/neural_chat/tests/ci/plugins/retrieval/test_build_chatbot.py
  intel_extension_for_transformers/neural_chat/tests/ci/plugins/retrieval/test_inference.py
  intel_extension_for_transformers/neural_chat/tests/ci/plugins/retrieval/test_parameters.py
  intel_extension_for_transformers/neural_chat/tests/ci/plugins/retrieval/test_rag.py
  intel_extension_for_transformers/neural_chat/tests/nightly/plugins/retrieval/test_build_chatbot.py
  intel_extension_for_transformers/neural_chat/tests/nightly/plugins/retrieval/test_inference.py
  intel_extension_for_transformers/neural_chat/tests/nightly/plugins/retrieval/test_parameters.py
  intel_extension_for_transformers/neural_chat/tests/nightly/plugins/retrieval/test_rag.py
  intel_extension_for_transformers/neural_chat/tests/nightly/plugins/retrieval/test_retrieval.py
Labels: NeuralChat, ITREX1.3.2

#1293 [NeuralChat] CUDA serving with Triton Inference Server
  intel_extension_for_transformers/neural_chat/examples/serving/triton_inference_sever/cuda/README.md
  intel_extension_for_transformers/neural_chat/serving/triton/text_generation/cuda/config.pbtxt
  intel_extension_for_transformers/neural_chat/serving/triton/text_generation/cuda/model.py
Labels: ITREX1.3.2

#1182 [Neuralchat] Notebook retrieval update
  intel_extension_for_transformers/neural_chat/docker/Dockerfile
  intel_extension_for_transformers/neural_chat/docs/notebooks/build_chatbot_on_habana_gaudi.ipynb
  intel_extension_for_transformers/neural_chat/docs/notebooks/build_chatbot_on_icx.ipynb
  intel_extension_for_transformers/neural_chat/docs/notebooks/build_chatbot_on_nv_a100.ipynb
  intel_extension_for_transformers/neural_chat/docs/notebooks/build_chatbot_on_spr.ipynb
  intel_extension_for_transformers/neural_chat/docs/notebooks/build_chatbot_on_xpu.ipynb
  intel_extension_for_transformers/neural_chat/docs/notebooks/customize_chatbot_with_plugins.ipynb
  intel_extension_for_transformers/neural_chat/models/model_utils.py
  intel_extension_for_transformers/neural_chat/requirements_hpu.txt
Labels: ITREX1.3.2

#1270 [NeuralChat] Enable bm25 sparse retrieval, enable retrieval then rerank pipeline
  intel_extension_for_transformers/langchain/retrievers/__init__.py
  intel_extension_for_transformers/langchain/retrievers/bge_reranker.py
  intel_extension_for_transformers/langchain/retrievers/child_parent_retriever.py
  intel_extension_for_transformers/langchain/retrievers/vectorstore_retriever.py
  intel_extension_for_transformers/neural_chat/pipeline/plugins/retrieval/README.md
  intel_extension_for_transformers/neural_chat/pipeline/plugins/retrieval/requirements.txt
  intel_extension_for_transformers/neural_chat/pipeline/plugins/retrieval/retrieval_agent.py
  intel_extension_for_transformers/neural_chat/pipeline/plugins/retrieval/retriever_adapter.py
  intel_extension_for_transformers/neural_chat/tests/requirements.txt
Labels: NeuralChat, ITREX1.3.2

#1245 [NeuralChat] enable gramma check and query polish to enhance RAG performance
  intel_extension_for_transformers/neural_chat/pipeline/plugins/prompt/prompt_template.py
  intel_extension_for_transformers/neural_chat/pipeline/plugins/retrieval/detector/query_explainer.py
  intel_extension_for_transformers/neural_chat/pipeline/plugins/retrieval/retrieval_agent.py
  intel_extension_for_transformers/neural_chat/prompts/prompt.py
  intel_extension_for_transformers/neural_chat/tests/ci/plugins/retrieval/test_retrieval.py
Labels: NeuralChat, ITREX1.3.2

#1305 Update requirements
  .github/workflows/chatbot-finetune-mpt-7b-chat-hpu.yml
  .github/workflows/chatbot-finetune-mpt-7b-chat.yml
  .github/workflows/chatbot-inference-llama-2-7b-chat-hf.yml
  .github/workflows/chatbot-inference-llama-2-7b_70b-chat-hf-hpu.yml
  .github/workflows/chatbot-inference-mpt-7b-chat-hpu.yml
  .github/workflows/chatbot-inference-mpt-7b-chat.yml
  .github/workflows/script/unitTest/run_unit_test_neuralchat.sh
  docker/Dockerfile_code_gen
  examples/huggingface/pytorch/text-generation/quantization/run_benchmark.sh
  examples/huggingface/pytorch/text-generation/quantization/run_tuning.sh
  intel_extension_for_transformers/neural_chat/README.md
  intel_extension_for_transformers/neural_chat/requirements.txt
  intel_extension_for_transformers/neural_chat/requirements_cpu.txt
  intel_extension_for_transformers/neural_chat/requirements_hpu.txt
  intel_extension_for_transformers/neural_chat/requirements_pc.txt
  intel_extension_for_transformers/neural_chat/requirements_xpu.txt
  intel_extension_for_transformers/neural_chat/tests/requirements.txt
  intel_extension_for_transformers/neural_chat/ui/gradio/basic/README.md
  intel_extension_for_transformers/neural_chat/ui/gradio/basic/requirements.txt
Labels: ITREX1.3.2

#1294 update requirements_xpu.txt in neural chat to add neural_speed and ip…
  intel_extension_for_transformers/neural_chat/docs/notebooks/build_chatbot_on_xpu.ipynb
  intel_extension_for_transformers/neural_chat/docs/notebooks/deploy_chatbot_on_xpu.ipynb
  intel_extension_for_transformers/neural_chat/models/model_utils.py
  intel_extension_for_transformers/neural_chat/requirements_xpu.txt
Labels: ITREX1.3.2

#1298 [API Changed] Dispatch the backend based on model_type
  docs/qloracpu.md
  docs/smoothquant.md
  docs/weightonlyquant.md
  examples/huggingface/pytorch/code-generation/quantization/run_generation.py
  examples/huggingface/pytorch/text-generation/quantization/README.md
  examples/huggingface/pytorch/text-generation/quantization/run_generation.py
  examples/huggingface/pytorch/text-generation/quantization/run_generation_gpu_woq.py
  examples/huggingface/pytorch/text-generation/quantization/run_tuning.sh
  intel_extension_for_transformers/llm/finetuning/finetuning.py
  intel_extension_for_transformers/llm/quantization/optimization.py
  intel_extension_for_transformers/llm/runtime/neural_speed/tests/test_neural_speed.py
  intel_extension_for_transformers/neural_chat/README.md
  intel_extension_for_transformers/neural_chat/chatbot.py
  intel_extension_for_transformers/neural_chat/config.py
  intel_extension_for_transformers/neural_chat/docs/advanced_features.md
  intel_extension_for_transformers/neural_chat/docs/notebooks/build_talkingbot_on_pc.ipynb
  intel_extension_for_transformers/neural_chat/docs/notebooks/itrex_llm_graph_int4_optimization_on_spr.ipynb
  intel_extension_for_transformers/neural_chat/docs/notebooks/transformers_extension_api.ipynb
  intel_extension_for_transformers/neural_chat/docs/notebooks/workshop/01_quickstart_neuralchat.ipynb
  intel_extension_for_transformers/neural_chat/examples/deployment/codegen/backend/pc/gguf/README.md
  intel_extension_for_transformers/neural_chat/examples/deployment/codegen/backend/pc/gptq/README.md
  intel_extension_for_transformers/neural_chat/examples/deployment/codegen/backend/pc/gptq/codegen.yaml
  intel_extension_for_transformers/neural_chat/examples/deployment/codegen/backend/pc/woq/README.md
  intel_extension_for_transformers/neural_chat/examples/deployment/codegen/backend/pc/woq/codegen.yaml
  intel_extension_for_transformers/neural_chat/examples/deployment/photo_ai/backend/photoai.yaml
  intel_extension_for_transformers/neural_chat/examples/deployment/textbot/backend/xeon/textbot.yaml
  intel_extension_for_transformers/neural_chat/examples/deployment/textbot/backend_with_cache/textbot.yaml
  intel_extension_for_transformers/neural_chat/models/base_model.py
  intel_extension_for_transformers/neural_chat/models/model_utils.py
  intel_extension_for_transformers/neural_chat/server/neuralchat_server.py
  intel_extension_for_transformers/neural_chat/tests/ci/models/test_model_utils.py
  intel_extension_for_transformers/neural_chat/tests/ci/optimization/test_optimization.py
  intel_extension_for_transformers/neural_chat/tests/ci/optimization/test_optimization_llmruntime.py
  intel_extension_for_transformers/neural_chat/tests/ci/server/test_itrex_int4_textchat_server.py
  intel_extension_for_transformers/neural_chat/tests/ci/server/test_itrex_llm_runtime_int4_server.py
  intel_extension_for_transformers/neural_chat/tests/nightly/models/test_gptq.py
  intel_extension_for_transformers/transformers/modeling/modeling_auto.py
  intel_extension_for_transformers/transformers/utils/config.py
  tests/CI/test_quantization.py
  tests/CI/test_weight_only.py
  tests/CI/test_weight_only_gpu.py
  tests/Nightly/test_llm_runtime.py
  tests/Nightly/test_llm_smoothquant.py
Labels: ITREX1.3.2

#1225 Dev/ipex woq
  .github/workflows/script/formatScan/pylint.sh
  .github/workflows/script/unitTest/coverage/.neural-chat-coveragerc
  examples/huggingface/pytorch/text-generation/quantization/run_generation_gpu_woq.py
  intel_extension_for_transformers/llm/quantization/utils.py
  intel_extension_for_transformers/llm/utils/generation/__init__.py
  intel_extension_for_transformers/llm/utils/generation/beam_search.py
  intel_extension_for_transformers/llm/utils/generation/greedy_search.py
  intel_extension_for_transformers/transformers/modeling/llava_models/llava_mistral.py
  intel_extension_for_transformers/transformers/modeling/modeling_auto.py
  intel_extension_for_transformers/transformers/utils/config.py
  intel_extension_for_transformers/transformers/utils/utility.py
  tests/CI/test_weight_only.py
  tests/CI/test_weight_only_gpu.py
Labels: WIP

#1280 upgrade pytorch/ipex to 2.2.0
  .github/workflows/script/unitTest/run_unit_test_neuralchat.sh
  .github/workflows/script/unitTest/run_unit_test_neuralspeed.sh
  docker/Dockerfile_code_gen
  examples/huggingface/neural_speed/perplexity/requirements.txt
  examples/huggingface/neural_speed/requirements.txt
  examples/huggingface/pytorch/image-classification/deployment/imagenet/vit/requirements.txt
  examples/huggingface/pytorch/image-classification/quantization/requirements.txt
  examples/huggingface/pytorch/language-modeling/deployment/fill-mask/electra_base_chinese/requirements.txt
  examples/huggingface/pytorch/question-answering/deployment/squad/bert_large/requirements.txt
  examples/huggingface/pytorch/question-answering/deployment/squad/length_adaptive_transformer/requirements.txt
  examples/huggingface/pytorch/question-answering/dynamic/requirements.txt
  examples/huggingface/pytorch/question-answering/pruning/basic_magnitude/requirements.txt
  examples/huggingface/pytorch/question-answering/pruning/longformer_triviaqa/requirements.txt
  examples/huggingface/pytorch/summarization/quantization/requirements.txt
  examples/huggingface/pytorch/text-classification/cascade-models/requirements.txt
  examples/huggingface/pytorch/text-classification/deployment/emotion/distilbert_base_uncased/requirements.txt
  examples/huggingface/pytorch/text-classification/deployment/mrpc/bert_base/requirements.txt
  examples/huggingface/pytorch/text-classification/deployment/mrpc/bert_base_cased/requirements.txt
  examples/huggingface/pytorch/text-classification/deployment/mrpc/bert_mini/requirements.txt
  examples/huggingface/pytorch/text-classification/deployment/mrpc/distilbert_base_uncased/requirements.txt
  examples/huggingface/pytorch/text-classification/deployment/mrpc/roberta_base/requirements.txt
  examples/huggingface/pytorch/text-classification/deployment/sparse/bert_mini/requirements.txt
  examples/huggingface/pytorch/text-classification/deployment/sparse/distilbert_base_uncased/requirements.txt
  examples/huggingface/pytorch/text-classification/deployment/sst2/bert_mini/requirements.txt
  examples/huggingface/pytorch/text-classification/deployment/sst2/distilbert_base_uncased/requirements.txt
  examples/huggingface/pytorch/text-classification/deployment/sst2/minilm_l6_h384_uncased/requirements.txt
  examples/huggingface/pytorch/text-classification/early-exit/requirements.txt
  examples/huggingface/pytorch/text-classification/new_pruning/requirements.txt
  examples/huggingface/pytorch/text-classification/orchestrate_optimizations/requirements.txt
  examples/huggingface/pytorch/text-classification/pruning/requirements.txt
  examples/huggingface/pytorch/text-classification/quantization/ptq/requirements.txt
  examples/huggingface/pytorch/text-classification/quantization/qat/requirements.txt
  examples/huggingface/pytorch/text-classification/quantization/requirements.txt
  examples/huggingface/pytorch/text-embedding/deployment/mteb/bge/requirements.txt
  examples/huggingface/pytorch/text-to-image/deployment/stable_diffusion/requirements.txt
  examples/huggingface/pytorch/textual-inversion/quantization/requirements.txt
  examples/huggingface/pytorch/token-classification/quantization/requirements.txt
  examples/huggingface/pytorch/translation/quantization/requirements.txt
  intel_extension_for_transformers/llm/runtime/neural_speed/requirements.txt
  intel_extension_for_transformers/neural_chat/README.md
  intel_extension_for_transformers/neural_chat/docker/inference/README.md
  intel_extension_for_transformers/neural_chat/examples/deployment/codegen/backend/xeon/README.md
  intel_extension_for_transformers/neural_chat/examples/deployment/plugin/image2image/requirements.txt
  intel_extension_for_transformers/neural_chat/examples/finetuning/instruction/README.md
  intel_extension_for_transformers/neural_chat/examples/finetuning/instruction/requirements.txt
  intel_extension_for_transformers/neural_chat/requirements.txt
  intel_extension_for_transformers/neural_chat/requirements_cpu.txt
  intel_extension_for_transformers/neural_chat/requirements_pc.txt
  intel_extension_for_transformers/neural_chat/tests/requirements.txt
  intel_extension_for_transformers/neural_chat/ui/gradio/basic/requirements.txt
  requirements.txt
  tests/requirements.txt
  workflows/chatbot/fine_tuning/README.md
  workflows/hf_finetuning_and_inference_nlp/requirements.txt
Labels: WIP

#1318 Add MLPerf Example
  examples/mlperf/neural_speed/README.md
Labels: ready for merge

#1310 [NeuralChat] Support chatbot inference with huggingface endpoint
  intel_extension_for_transformers/neural_chat/chatbot.py
  intel_extension_for_transformers/neural_chat/config.py
  intel_extension_for_transformers/neural_chat/errorcode.py
  intel_extension_for_transformers/neural_chat/models/base_model.py
  intel_extension_for_transformers/neural_chat/models/huggingface_model.py
  intel_extension_for_transformers/neural_chat/requirements_cpu.txt
  intel_extension_for_transformers/neural_chat/requirements_hpu.txt
  intel_extension_for_transformers/neural_chat/requirements_pc.txt
  intel_extension_for_transformers/neural_chat/requirements_xpu.txt
Labels: WIP
